CanModule: CanInterfaceImplementations/anagate/AnaCanScan.cpp File Reference
AnaCanScan.cpp File Reference
#include "AnaCanScan.h"
Macros
#define DLLEXPORTFLAG
#define WINAPI
#define MLOGANA(LEVEL, THIS) LOG(Log::LEVEL, AnaCanScan::st_logItHandleAnagate) << __FUNCTION__ << " " << " anagate bus= " << THIS->getBusName() << " "
Functions
DLLEXPORTFLAG CCanAccess * getCanBusAccess ()
void WINAPI InternalCallback (AnaUInt32 nIdentifier, const char *pcBuffer, AnaInt32 nBufferLen, AnaInt32 nFlags, AnaInt32 hHandle, AnaInt32 nSeconds, AnaInt32 nMicroseconds)
Variables
std::recursive_mutex anagateReconnectMutex
std::map< AnaInt32, AnaCanScan * > g_AnaCanScanObjectMap
Macro Definition Documentation
DLLEXPORTFLAG
#define DLLEXPORTFLAG
© Copyright CERN, 2015. All rights not expressly granted are reserved.
AnaCanScan.cpp
Created on: Mar 17, 2015 Author: pnikiel, vfilimon, quasar team Maintainer: mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
Here the Anagate ethernet-CAN bridges are implemented
Definition at line 32 of file AnaCanScan.cpp.
MLOGANA
#define MLOGANA (LEVEL, THIS) LOG(Log::LEVEL, AnaCanScan::st_logItHandleAnagate) << __FUNCTION__ << " " << " anagate bus= " << THIS->getBusName() << " "
Definition at line 53 of file AnaCanScan.cpp.
WINAPI
#define WINAPI
Definition at line 33 of file AnaCanScan.cpp.
Function Documentation
getCanBusAccess()
DLLEXPORTFLAG CCanAccess* getCanBusAccess ()
creates and returns anagate can access object
Definition at line 151 of file AnaCanScan.cpp.
InternalCallback()
void WINAPI InternalCallback (AnaUInt32 nIdentifier, const char * pcBuffer, AnaInt32 nBufferLen, AnaInt32 nFlags, AnaInt32 hHandle, AnaInt32 nSeconds, AnaInt32 nMicroseconds)
call back to catch incoming CAN messages for reading. It is called on a handle, which is internally registered and managed by the anagate API. If that handle changes, the callback has to be unregistered before I guess.
Definition at line 162 of file AnaCanScan.cpp.
References CanMsgStruct::c_data, CanMsgStruct::c_dlc, CanMsgStruct::c_ff, CanMsgStruct::c_id, CanMsgStruct::c_time, CanModule::canMessageToString(), CanModule::convertTimepointToTimeval(), CanModule::currentTimeTimeval(), and g_AnaCanScanObjectMap.
Referenced by AnaCanScan::connectReceptionHandler(), and AnaCanScan::openCanPort().
Variable Documentation
anagateReconnectMutex
std::recursive_mutex anagateReconnectMutex
Definition at line 37 of file AnaCanScan.cpp.
Referenced by AnaCanScan::reconnectAllPorts().
g_AnaCanScanObjectMap
std::map<AnaInt32, AnaCanScan*> g_AnaCanScanObjectMap
global map of connection-objects: the map-key is the handle. Since handles are allocated by the OS the keys are getting changed as well when we reconnect, so that we do not keep the stale keys(=handles) in the map at all. The map is used in the (static) InternalCallback code straightforward and speedy, because we can get to the object by just looking up the map using the key(=the handle). The map manipulations are protected by serialization of reconnects with the anagateReconnectMutex. At RO access in the callbacks the map is NOT protected because we do not want to serialize the callbacks and because it is a RO map access, which is "like atomic". Well - it does work in multithreads.. ;-)
Definition at line 51 of file AnaCanScan.cpp.
Referenced by AnaCanScan::connectReceptionHandler(), AnaCanScan::eraseReceptionHandlerFromMap(), InternalCallback(), AnaCanScan::openCanPort(), AnaCanScan::reconnectAllPorts(), AnaCanScan::reconnectThisPort(), and AnaCanScan::showAnaCanScanObjectMap().