CanModule: STCanScan Class Reference
STCanScan Class Reference
#include <STCanScan.h>
Public Member Functions
STCanScan ()
STCanScan (STCanScan const &other)=delete
STCanScan & operator= (STCanScan const &other)=delete
virtual ~STCanScan ()
virtual int createBus (const string name, const string parameters)
virtual bool sendMessage (short cobID, unsigned char len, unsigned char *message, bool rtr=false)
virtual bool sendRemoteRequest (short cobID)
virtual void getStatistics (CanStatistics &result)
virtual uint32_t getPortStatus ()
virtual uint32_t getPortBitrate ()
Log::LogComponentHandle logItHandle ()
virtual void setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action)
virtual void setReconnectReceptionTimeout (unsigned int timeout)
virtual void setReconnectFailedSendCount (unsigned int c)
virtual CanModule::ReconnectAutoCondition getReconnectCondition ()
virtual CanModule::ReconnectAction getReconnectAction ()
Public Member Functions inherited from CanModule::CCanAccess
CCanAccess ()
virtual bool sendMessage (CanMessage *canm)
std::string & getBusName ()
virtual ~CCanAccess ()
bool initialiseLogging (LogItInstance *remoteInstance)
LogItInstance * getLogItInstance ()
vector< string > parseNameAndParameters (string name, string parameters)
Private Member Functions
bool sendErrorCode (long)
int configureCanBoard (const string name, const string parameters)
int openCanPort (tUcanInitCanParam initializationParameters)
bool errorCodeToString (long error, char message[])
unsigned int vendorBaudRate2UserBaudRate (unsigned int vb)
std::string STcanGetErrorText (long errCode)
Static Private Member Functions
static DWORD WINAPI CanScanControlThread (LPVOID pCanScan)
static tUcanInitCanParam createInitializationParameters (unsigned int br)
static void setCanHandleInUse (int n, bool t)
static bool isCanHandleInUse (int n)
static void setCanHandle (int n, tUcanHandle tU)
static tUcanHandle getCanHandle (int n)
static int reconnectAllPorts (tUcanHandle h)
Private Attributes
int m_moduleNumber
int m_channelNumber
int m_canHandleNumber
tUcanHandle m_UcanHandle
CanStatistics m_statistics
unsigned int m_baudRate
Log::LogComponentHandle m_logItHandleSt
DWORD m_busStatus
bool m_CanScanThreadShutdownFlag
HANDLE m_hCanScanThread
DWORD m_idCanScanThread
Static Private Attributes
static tUcanHandle s_canHandleArray [256]
static bool s_isCanHandleInUseArray [256]
The macro below is applicable only to this translation unit.
Additional Inherited Members
Public Attributes inherited from CanModule::CCanAccess
boost::signals2::signal< void(const CanMessage &) > canMessageCame
boost::signals2::signal< void(const int, const char *, timeval &) > canMessageError
Protected Member Functions inherited from CanModule::CCanAccess
bool hasTimeoutOnReception ()
void resetTimeoutOnReception ()
void resetTimeNow ()
Static Protected Member Functions inherited from CanModule::CCanAccess
static std::string reconnectConditionString (CanModule::ReconnectAutoCondition c)
static std::string reconnectActionString (CanModule::ReconnectAction c)
Protected Attributes inherited from CanModule::CCanAccess
string m_sBusName
CanParameters m_CanParameters
CanModule::ReconnectAutoCondition m_reconnectCondition
CanModule::ReconnectAction m_reconnectAction
unsigned int m_timeoutOnReception
int m_triggerCounter
unsigned int m_failedSendCounter
Detailed Description
Definition at line 39 of file STCanScan.h.
Constructor & Destructor Documentation
STCanScan() [1/2]
STCanScan::STCanScan ()
Definition at line 58 of file STCanScan.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CCanAccess::m_failedSendCounter, m_statistics, CanModule::CCanAccess::m_triggerCounter, and CanModule::CanStatistics::setTimeSinceOpened().
STCanScan() [2/2]
STCanScan::STCanScan (STCanScan const & other) delete
~STCanScan()
STCanScan::~STCanScan () virtual
Definition at line 166 of file STCanScan.cpp.
References m_CanScanThreadShutdownFlag, m_channelNumber, m_hCanScanThread, m_UcanHandle, and MLOGST.
Member Function Documentation
CanScanControlThread()
DWORD WINAPI STCanScan::CanScanControlThread (LPVOID pCanScan) static private
thread to supervise port activity
lets check the timeoutOnReception reconnect condition. If it is true, all we can do is to close/open the port again since the underlying hardware is hidden by socketcan abstraction. Like his we do not have to pollute the "sendMessage" like for anagate, and that is cleaner.
Definition at line 95 of file STCanScan.cpp.
References CanMsgStruct::c_data, CanMsgStruct::c_dlc, CanMsgStruct::c_ff, CanMsgStruct::c_id, CanMsgStruct::c_time, CanModule::CCanAccess::canMessageCame, CanModule::convertTimepointToTimeval(), createInitializationParameters(), CanModule::currentTimeTimeval(), getReconnectAction(), getReconnectCondition(), CanModule::CCanAccess::hasTimeoutOnReception(), m_baudRate, m_CanScanThreadShutdownFlag, m_channelNumber, m_moduleNumber, m_statistics, m_UcanHandle, MLOGST, CanModule::CanStatistics::onReceive(), openCanPort(), CanModule::CCanAccess::reconnectActionString(), CanModule::CCanAccess::reconnectConditionString(), CanModule::CCanAccess::resetTimeoutOnReception(), sendErrorCode(), setCanHandleInUse(), CanModule::CanStatistics::setTimeSinceReceived(), CanModule::singleBus, and CanModule::timeoutOnReception.
Referenced by createBus().
configureCanBoard()
int STCanScan::configureCanBoard (const string name, const string parameters) private
configures systec @ windows board only G1/G2 boards
Definition at line 242 of file STCanScan.cpp.
References createInitializationParameters(), m_baudRate, m_canHandleNumber, CanModule::CCanAccess::m_CanParameters, m_channelNumber, CanModule::CanParameters::m_iNumberOfDetectedParameters, CanModule::CanParameters::m_lBaudRate, m_moduleNumber, MLOGST, openCanPort(), CanModule::CCanAccess::parseNameAndParameters(), and vendorBaudRate2UserBaudRate().
Referenced by createBus().
createBus()
int STCanScan::createBus (const string name, const string parameters) virtual
Method that initialises a CAN bus channel for systec@windows. All following methods called on the same object will be using this initialized channel.
Parameters
name = 2 parameters separated by ":" like "n0:n1"
n0 = "st" for systec@windows
n1 = CAN port number on the module, can be prefixed with "can"
ex.: "st:can1" speaks to port 1 on systec module at the ip
ex.: "st:1" works as well
parameters one parameter: "p0", positive integers
"Unspecified" (or empty): using defaults = "125000" // params missing
p0: bitrate: 50000, 100000, 125000, 250000, 500000, 1000000 bit/s i.e. "250000"
Returns
was the initialisation process successful?
===note from Piotr=== in the Windows implementation of Systec (hardware component: st): to define the interface naming as canX, where X is a non-negative number note: the SysTec driver for windows expects addressing in terms of module number and channel (e.g. 0:0 is can0, 1:0 is can2, 1:1 is can3, etc) so can0 should open a SysTec interface 0:0 matching "can0" on the box, can1 should open a SysTec interface 0:1 matching "can1" on the box, etc.
returns: 0 = OK, bus created -1 = not ok, board init failed -2 = not ok, thread creation failed
no implemented: 1=OK, bus creation skipped since it exists already
Implements CanModule::CCanAccess.
Definition at line 208 of file STCanScan.cpp.
References CanScanControlThread(), configureCanBoard(), CanModule::LogItComponentName, m_hCanScanThread, m_idCanScanThread, m_logItHandleSt, CanModule::CCanAccess::m_sBusName, and MLOGST.
createInitializationParameters()
tUcanInitCanParam STCanScan::createInitializationParameters (unsigned int baudRate) static private
We create and fill initializationParameters, to pass it to openCanPort
Definition at line 75 of file STCanScan.cpp.
Referenced by CanScanControlThread(), configureCanBoard(), and sendMessage().
errorCodeToString()
bool STCanScan::errorCodeToString (long error, char message[]) private
convert the systec status word into a human readable message
Definition at line 687 of file STCanScan.cpp.
References STcanGetErrorText().
Referenced by sendErrorCode().
getCanHandle()
static tUcanHandle STCanScan::getCanHandle (int n) inline static private
Definition at line 103 of file STCanScan.h.
Referenced by openCanPort().
getPortBitrate()
virtual uint32_t STCanScan::getPortBitrate () inline virtual
returns the bitrate of that port [bits/sec] according to what CanModule buffers say. This is the setting used for setting up the hardware, after any default rules have been applied, but BEFORE any vendor specific encoding into obscure bitpatterns occurs. This happens at port opening and the bitrate can only be changed at that moment. So please call this method just after you have opened the port. But also since there is no hw interaction and it just returns a buffer, you may call it as often as you like. Default bitrate is always 125000bits/s if "Unspecified"
Implements CanModule::CCanAccess.
Definition at line 61 of file STCanScan.h.
getPortStatus()
uint32_t STCanScan::getPortStatus () virtual
get CAN port and USB status, code it into an int > 200 (for windows@systec). use the API directly table19 says for CAN status: 0x0: no error 0x1: tx overrun 0x2: rx overrun 0x4: error limit1 exceeded: warning limit 0x8: error limit2 exceeded: error passive 0x10: can controller is off 0x40: rx buffer overrun 0x80: tx buffer overrun 0x400: transmit timeout, message dropped
table20 says for USB status: 0x2000: module/usb got reset because of polling failure per second 0x4000: module/usb got reset because watchdog was not triggered
Implements CanModule::CCanAccess.
Definition at line 369 of file STCanScan.cpp.
References CANMODULE_STATUS_BP_SYSTEC, and m_UcanHandle.
getReconnectAction()
virtual CanModule::ReconnectAction STCanScan::getReconnectAction () inline virtual
read back the r.action
Implements CanModule::CCanAccess.
Definition at line 71 of file STCanScan.h.
Referenced by CanScanControlThread().
getReconnectCondition()
virtual CanModule::ReconnectAutoCondition STCanScan::getReconnectCondition () inline virtual
read back the r.condition
Implements CanModule::CCanAccess.
Definition at line 70 of file STCanScan.h.
Referenced by CanScanControlThread().
getStatistics()
void STCanScan::getStatistics (CanStatistics & result) virtual
Implements CanModule::CCanAccess.
Definition at line 695 of file STCanScan.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CanStatistics::computeDerived(), m_baudRate, and m_statistics.
isCanHandleInUse()
static bool STCanScan::isCanHandleInUse (int n) inline static private
Definition at line 101 of file STCanScan.h.
Referenced by openCanPort().
logItHandle()
Log::LogComponentHandle STCanScan::logItHandle () inline
Definition at line 63 of file STCanScan.h.
openCanPort()
int STCanScan::openCanPort (tUcanInitCanParam initializationParameters) private
Obtains a Systec canport and opens it. The name of the port and parameters should have been specified by preceding call to configureCanboard()
Returns
less than zero in case of error, otherwise success
Definition at line 318 of file STCanScan.cpp.
References getCanHandle(), isCanHandleInUse(), m_channelNumber, m_moduleNumber, m_statistics, m_UcanHandle, MLOGST, setCanHandle(), setCanHandleInUse(), and CanModule::CanStatistics::setTimeSinceOpened().
Referenced by CanScanControlThread(), configureCanBoard(), and sendMessage().
operator=()
STCanScan& STCanScan::operator= (STCanScan const & other) delete
reconnectAllPorts()
int STCanScan::reconnectAllPorts (tUcanHandle h) static private
hard reset the bridge and reconnect all ports and handlers: windows
Definition at line 395 of file STCanScan.cpp.
References m_moduleNumber, and m_UcanHandle.
Referenced by sendMessage().
sendErrorCode()
bool STCanScan::sendErrorCode (long status) private
Definition at line 377 of file STCanScan.cpp.
References CanModule::CCanAccess::canMessageError, CanModule::convertTimepointToTimeval(), CanModule::currentTimeTimeval(), errorCodeToString(), and m_busStatus.
Referenced by CanScanControlThread(), sendMessage(), and sendRemoteRequest().
sendMessage()
bool STCanScan::sendMessage (short cobID, unsigned char len, unsigned char * message, bool rtr = false) virtual
Method that sends a message trough the can bus channel. If the method createBUS was not called before this, sendMessage will fail, as there is no can bus channel to send a message through.
Parameters
cobID Identifier that will be used for the message.
len Length of the message. If the message is bigger than 8 characters, it will be split into separate 8 characters messages.
message Message to be sent trough the can bus.
rtr is the message a remote transmission request?
Returns
Was the sending process successful?
Implements CanModule::CCanAccess.
Definition at line 428 of file STCanScan.cpp.
References CanModule::allBusesOnBridge, createInitializationParameters(), m_baudRate, m_channelNumber, CanModule::CCanAccess::m_failedSendCounter, CanModule::CCanAccess::m_reconnectAction, CanModule::CCanAccess::m_reconnectCondition, m_statistics, CanModule::CCanAccess::m_triggerCounter, m_UcanHandle, MLOGST, CanModule::never, CanModule::CanStatistics::onTransmit(), openCanPort(), CanModule::CCanAccess::reconnectActionString(), reconnectAllPorts(), CanModule::CCanAccess::reconnectConditionString(), sendErrorCode(), CanModule::sendFail, CanModule::CanStatistics::setTimeSinceTransmitted(), and CanModule::singleBus.
sendRemoteRequest()
bool STCanScan::sendRemoteRequest (short cobID) virtual
Method that sends a remote request trough the can bus channel. If the method createBus was not called before this, sendMessage will fail, as there is no can bus channel to send the request trough. Similar to sendMessage, but it sends an special message reserved for requests.
Parameters
cobID Identifier that will be used for the request.
Returns
: Was the initialisation process successful?
Implements CanModule::CCanAccess.
Definition at line 510 of file STCanScan.cpp.
References m_channelNumber, m_UcanHandle, and sendErrorCode().
setCanHandle()
static void STCanScan::setCanHandle (int n, tUcanHandle tU) inline static private
Definition at line 102 of file STCanScan.h.
Referenced by openCanPort().
setCanHandleInUse()
static void STCanScan::setCanHandleInUse (int n, bool t) inline static private
Definition at line 100 of file STCanScan.h.
Referenced by CanScanControlThread(), and openCanPort().
setReconnectBehavior()
virtual void STCanScan::setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action) inline virtual
configuring the reconnection behavior: a condition triggers an action. The implementation is implementation-specific because not all vendor APIs permit the same behavior: not all combinations are available for all vendors/implementations. The implemented reconnection behavior is standardized nevertheless: "you get what you see". Foe each CanBus you have to choose one condition and one action. Condition detection and action execution are then automatic inside CanModule.
Parameters
CanModule::ReconnectAutoCondition cond
sendFail (default): a reconnection is triggered automatically if a send on the canBus fails. The number of failed sends can be set (default is 10). The failed sending must be strictly consecutive, if there is a succeeded sending, the internal counting restarts.
timeoutOnReception: the last time of a successful reception on a given channel can be monitored. If the last reception is older than 120 sec a reset is triggered automatically. This last successful reception time is calculated each time a send is invoked. The timeout is specified in seconds, default is 120sec.
never: this condition is always false and therefore no automatic reconnection action will be triggered. You can still call the explicit method reconnect(<action>) but it is up to the client (server) to decide when.
CanModule::ReconnectAction action
singleBus (default): a single connection (canbus, channel) is reset and reception handler is reconnected.
wholeBridge if available, the whole bridge is reset, affecting all physical channels on that bridge. Only available for anagate. If a bridge is shared between multiple tasks, all channels across tasks are reset, affecting all tasks connected to that bridge. Evidently, a given channel must only be used by at most one task.
Implements CanModule::CCanAccess.
Definition at line 64 of file STCanScan.h.
setReconnectFailedSendCount()
virtual void STCanScan::setReconnectFailedSendCount (unsigned int c) inline virtual
set the counter for failed consecutive sending attempts, for reconnection. default is 10.
Implements CanModule::CCanAccess.
Definition at line 69 of file STCanScan.h.
setReconnectReceptionTimeout()
virtual void STCanScan::setReconnectReceptionTimeout (unsigned int timeout) inline virtual
set the timout interval for message reception, for the reconnection behaviour. Units is seconds, default is 120.
Implements CanModule::CCanAccess.
Definition at line 68 of file STCanScan.h.
STcanGetErrorText()
std::string STCanScan::STcanGetErrorText (long errCode) private
error text specific to STcan according to table24 I am just copying the whole descriptions from the doc, verbatim, wtf. you get some shakespeare from it.
Definition at line 527 of file STCanScan.cpp.
Referenced by errorCodeToString().
vendorBaudRate2UserBaudRate()
unsigned int STCanScan::vendorBaudRate2UserBaudRate (unsigned int vb) private
unfortunately it is necessary to convert the vendor baudrate back to the human readable user baudrate for statistics. we use presently ONLY G1/G2 boards (see usbcan.h)
Definition at line 290 of file STCanScan.cpp.
References MLOGST.
Referenced by configureCanBoard().
Member Data Documentation
m_baudRate
unsigned int STCanScan::m_baudRate private
Definition at line 80 of file STCanScan.h.
Referenced by CanScanControlThread(), configureCanBoard(), getStatistics(), and sendMessage().
m_busStatus
DWORD STCanScan::m_busStatus private
Definition at line 84 of file STCanScan.h.
Referenced by sendErrorCode().
m_canHandleNumber
int STCanScan::m_canHandleNumber private
Definition at line 77 of file STCanScan.h.
Referenced by configureCanBoard().
m_CanScanThreadShutdownFlag
bool STCanScan::m_CanScanThreadShutdownFlag private
Definition at line 85 of file STCanScan.h.
Referenced by CanScanControlThread(), and ~STCanScan().
m_channelNumber
int STCanScan::m_channelNumber private
Definition at line 76 of file STCanScan.h.
Referenced by CanScanControlThread(), configureCanBoard(), openCanPort(), sendMessage(), sendRemoteRequest(), and ~STCanScan().
m_hCanScanThread
HANDLE STCanScan::m_hCanScanThread private
Definition at line 87 of file STCanScan.h.
Referenced by createBus(), and ~STCanScan().
m_idCanScanThread
DWORD STCanScan::m_idCanScanThread private
Definition at line 89 of file STCanScan.h.
Referenced by createBus().
m_logItHandleSt
Log::LogComponentHandle STCanScan::m_logItHandleSt private
Definition at line 81 of file STCanScan.h.
Referenced by createBus().
m_moduleNumber
int STCanScan::m_moduleNumber private
Definition at line 71 of file STCanScan.h.
Referenced by CanScanControlThread(), configureCanBoard(), openCanPort(), and reconnectAllPorts().
m_statistics
CanStatistics STCanScan::m_statistics private
Definition at line 79 of file STCanScan.h.
Referenced by CanScanControlThread(), getStatistics(), openCanPort(), sendMessage(), and STCanScan().
m_UcanHandle
tUcanHandle STCanScan::m_UcanHandle private
Definition at line 78 of file STCanScan.h.
Referenced by CanScanControlThread(), getPortStatus(), openCanPort(), reconnectAllPorts(), sendMessage(), sendRemoteRequest(), and ~STCanScan().
s_canHandleArray
tUcanHandle STCanScan::s_canHandleArray static private
Definition at line 105 of file STCanScan.h.
s_isCanHandleInUseArray
bool STCanScan::s_isCanHandleInUseArray static private
The macro below is applicable only to this translation unit.
Copyright CERN, 2015. All rights not expressly granted are reserved.
STCanScap.cpp
Created on: Jul 21, 2011 Based on work by vfilimon Rework and logging done by Piotr Nikiel piotr.nosp@m.@nik.nosp@m.iel.i.nosp@m.nfo mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
Definition at line 106 of file STCanScan.h.
The documentation for this class was generated from the following files:
CanInterfaceImplementations/systec/STCanScan.h
CanInterfaceImplementations/systec/STCanScan.cpp