CanModule: CanModule::CanLibLoader Class Reference
CanModule::CanLibLoader Class Reference abstract
#include <CanLibLoader.h>
Public Member Functions
virtual ~CanLibLoader ()
SHARED_LIB_EXPORT_DEFN
CanModule::CCanAccess * openCanBus (std::string name, std::string parameters)
SHARED_LIB_EXPORT_DEFN void closeCanBus (CanModule::CCanAccess *cca)
void setLibName (std::string ln)
std::string getLibName ()
Static Public Member Functions
static SHARED_LIB_EXPORT_DEFN
CanLibLoader * createInstance (const std::string &libName)
Public Attributes
Log::LogComponentHandle lh
Protected Member Functions
CanLibLoader (const std::string &libName)
virtual void dynamicallyLoadLib (const std::string &libName)=0
virtual CCanAccess * createCanAccess ()=0
Private Attributes
std::string m_libName
Detailed Description
Definition at line 35 of file CanLibLoader.h.
Constructor & Destructor Documentation
CanModule::CanLibLoader::CanLibLoader (const std::string & libName) protected
Definition at line 39 of file CanLibLoader.cpp.
References lh, and CanModule::LogItComponentName.
CanModule::CanLibLoader::~CanLibLoader () virtual
Definition at line 45 of file CanLibLoader.cpp.
Member Function Documentation
void CanModule::CanLibLoader::closeCanBus (CanModule::CCanAccess * cca)
close a CAN bus
Definition at line 60 of file CanLibLoader.cpp.
References CanModule::Diag::delete_maps(), CanModule::CCanAccess::getBusName(), lh, and CanModule::CCanAccess::stopBus().
Referenced by CanModule::CanBusAccess::closeCanBus().
virtual CCanAccess* CanModule::CanLibLoader::createCanAccess () protected pure virtual
Implemented in CanModule::CanLibLoaderWin, and CanModule::CanLibLoaderLin.
Referenced by openCanBus().
CanLibLoader * CanModule::CanLibLoader::createInstance (const std::string & libName) static
creates an instance
Definition at line 47 of file CanLibLoader.cpp.
Referenced by CanModule::CanBusAccess::openCanBus().
virtual void CanModule::CanLibLoader::dynamicallyLoadLib (const std::string & libName) protected pure virtual
Implemented in CanModule::CanLibLoaderWin, and CanModule::CanLibLoaderLin.
std::string CanModule::CanLibLoader::getLibName () inline
Definition at line 56 of file CanLibLoader.h.
References m_libName.
Referenced by CanModule::Diag::delete_maps(), and CanModule::Diag::insert_maps().
CCanAccess * CanModule::CanLibLoader::openCanBus (std::string name, std::string parameters)
opens a can bus
Parameters
name,: Name of the can bus channel. The specific mapping will change depending on the interface used. For example, accessing channel 0 for the systec interface would be using name "st:9", while in socket can the same channel would be "sock:can0". anagate interface would be "an:0:192.168.1.2" for port A and ip address
parameters,: Different parameters used for the initialisation. For using the parameters present in the HW just set this to "Unspecified"
we could do 3 things here:
throw an exception and stop everything throw std::runtime_error("CanLibLoader::openCanBus: createBus Problem when opening canBus. stop.");
try again looping this would go on forever if the bus does not come up
ignore the bus and return 0 we return NULL in this case and the client has to check the pointer of course we decided to do that 6.april.2021 quasar meeting, related to https://its.cern.ch/jira/browse/OPCUA-2248
Definition at line 72 of file CanLibLoader.cpp.
References CanModule::CCanAccess::createBus(), createCanAccess(), CanModule::CCanAccess::initialiseLogging(), CanModule::Diag::insert_maps(), lh, and CanModule::LogItComponentName.
Referenced by CanModule::CanBusAccess::openCanBus().
void CanModule::CanLibLoader::setLibName (std::string ln) inline
Definition at line 55 of file CanLibLoader.h.
References m_libName.
Referenced by CanModule::CanLibLoaderLin::dynamicallyLoadLib(), and CanModule::CanLibLoaderWin::dynamicallyLoadLib().
Member Data Documentation
Log::LogComponentHandle CanModule::CanLibLoader::lh
Definition at line 53 of file CanLibLoader.h.
Referenced by CanLibLoader(), CanModule::CanLibLoaderLin::CanLibLoaderLin(), CanModule::CanLibLoaderWin::CanLibLoaderWin(), closeCanBus(), CanModule::CanLibLoaderLin::createCanAccess(), CanModule::CanLibLoaderWin::createCanAccess(), CanModule::CanLibLoaderLin::dynamicallyLoadLib(), CanModule::CanLibLoaderWin::dynamicallyLoadLib(), and openCanBus().
std::string CanModule::CanLibLoader::m_libName private
Definition at line 66 of file CanLibLoader.h.
Referenced by getLibName(), and setLibName().
The documentation for this class was generated from the following files:
CanLibLoader/include/CanLibLoader.h
CanLibLoader/src/CanLibLoader.cpp