CanModule: udevanalyserforpeak_ns::UdevAnalyserForPeak Class Reference
udevanalyserforpeak_ns::UdevAnalyserForPeak Class Reference
#include <UdevAnalyserForPeak.h>
Classes
struct PEAK_device_t
Static Public Member Functions
static UdevAnalyserForPeak * getInstance ()
static std::string peakExtendedIdentifierToSocketCanDevice (std::string portId)
static void showMap ()
Private Member Functions
UdevAnalyserForPeak ()
UdevAnalyserForPeak (const UdevAnalyserForPeak &)
virtual ~UdevAnalyserForPeak ()
void m_createUdevPortMap ()
unsigned int m_peakDeviceId (std::string s)
unsigned int m_peakSystemDeviceIndex (std::string s)
unsigned int m_peakLocalCanPort (std::string s)
unsigned int m_peakDriverNumber (std::string s)
unsigned int m_peakDeviceIdFromSystemDeviceIndex (unsigned int sd)
Static Private Member Functions
static bool m_peakStructCompare (PEAK_device_t peak1, PEAK_device_t peak2)
Static Private Attributes
static UdevAnalyserForPeak * m_instance_ptr = 0
static std::vector< PEAK_device_t > m_peak_v
static Log::LogComponentHandle m_logItHandleSock = 0
Detailed Description
Definition at line 19 of file UdevAnalyserForPeak.h.
Constructor & Destructor Documentation
UdevAnalyserForPeak() [1/2]
udevanalyserforpeak_ns::UdevAnalyserForPeak::UdevAnalyserForPeak () private
Definition at line 23 of file UdevAnalyserForPeak.cpp.
References CanModule::LogItComponentName, m_createUdevPortMap(), and m_logItHandleSock.
Referenced by getInstance().
UdevAnalyserForPeak() [2/2]
udevanalyserforpeak_ns::UdevAnalyserForPeak::UdevAnalyserForPeak (const UdevAnalyserForPeak &) private
~UdevAnalyserForPeak()
virtual udevanalyserforpeak_ns::UdevAnalyserForPeak::~UdevAnalyserForPeak () inline private virtual
Definition at line 52 of file UdevAnalyserForPeak.h.
Member Function Documentation
getInstance()
static UdevAnalyserForPeak* udevanalyserforpeak_ns::UdevAnalyserForPeak::getInstance () inline static
factory providing one singleton todo: use fancy threadsafe STATIC method
Definition at line 34 of file UdevAnalyserForPeak.h.
References m_instance_ptr, and UdevAnalyserForPeak().
Referenced by peakExtendedIdentifierToSocketCanDevice().
m_createUdevPortMap()
void udevanalyserforpeak_ns::UdevAnalyserForPeak::m_createUdevPortMap () private
this is where we do the udev call and construct a local-global port map which is system wide: need to scan for all pcan device links
now, build the map from results1: pcan-usb_pro_fd/0/can0 pcan-usb_pro_fd/devid=9054 pcan32 pcanusbpfd32 pcan-usb_pro_fd/1/can0 pcan-usb_pro_fd/devid=8910 pcan34 pcanusbpfd34
and result2: pcan-usb_pro_fd/0/can1 pcan33 pcanusbpfd33 pcan-usb_pro_fd/1/can1 pcan35 pcanusbpfd35
now we have to sort this with key=peakDriverNumber, since that is what socketcan does when assigning the socketcan devices
Definition at line 143 of file UdevAnalyserForPeak.cpp.
References udevanalyserforpeak_ns::UdevAnalyserForPeak::PEAK_device_t::deviceID, execcommand_ns::ExecCommand::getResults(), udevanalyserforpeak_ns::UdevAnalyserForPeak::PEAK_device_t::link, udevanalyserforpeak_ns::UdevAnalyserForPeak::PEAK_device_t::localCanPort, m_logItHandleSock, m_peak_v, m_peakDeviceId(), m_peakDeviceIdFromSystemDeviceIndex(), m_peakDriverNumber(), m_peakLocalCanPort(), m_peakStructCompare(), m_peakSystemDeviceIndex(), udevanalyserforpeak_ns::UdevAnalyserForPeak::PEAK_device_t::peakDriverNumber, and udevanalyserforpeak_ns::UdevAnalyserForPeak::PEAK_device_t::systemDeviceIndex.
Referenced by UdevAnalyserForPeak().
m_peakDeviceId()
unsigned int udevanalyserforpeak_ns::UdevAnalyserForPeak::m_peakDeviceId (std::string s) private
get the devids of the devices "9054" pcan-usb_pro_fd/0/can0 pcan-usb_pro_fd/devid=9054 pcan32 pcanusbpfd32
Definition at line 259 of file UdevAnalyserForPeak.cpp.
Referenced by m_createUdevPortMap().
m_peakDeviceIdFromSystemDeviceIndex()
unsigned int udevanalyserforpeak_ns::UdevAnalyserForPeak::m_peakDeviceIdFromSystemDeviceIndex (unsigned int sd) private
get the deviceID from the system driver number
Definition at line 218 of file UdevAnalyserForPeak.cpp.
References m_peak_v.
Referenced by m_createUdevPortMap().
m_peakDriverNumber()
unsigned int udevanalyserforpeak_ns::UdevAnalyserForPeak::m_peakDriverNumber (std::string s) private
get the local socket nb of the devices: "32" pcan-usb_pro_fd/0/can0 pcan-usb_pro_fd/devid=9054 pcan32 pcanusbpfd32
Definition at line 229 of file UdevAnalyserForPeak.cpp.
Referenced by m_createUdevPortMap().
m_peakLocalCanPort()
unsigned int udevanalyserforpeak_ns::UdevAnalyserForPeak::m_peakLocalCanPort (std::string s) private
get the local can port of the devices: the "0" of "can0" pcan-usb_pro_fd/0/can0 pcan-usb_pro_fd/devid=9054 pcan32 pcanusbpfd32
Definition at line 245 of file UdevAnalyserForPeak.cpp.
Referenced by m_createUdevPortMap().
m_peakStructCompare()
bool udevanalyserforpeak_ns::UdevAnalyserForPeak::m_peakStructCompare (PEAK_device_t peak1, PEAK_device_t peak2) static private
compares structs peak1 and peak2 and returns TRUE if the peak1->peakDriverNumber is SMALLER than peak2->peakDriverNumber .
Definition at line 135 of file UdevAnalyserForPeak.cpp.
References udevanalyserforpeak_ns::UdevAnalyserForPeak::PEAK_device_t::peakDriverNumber.
Referenced by m_createUdevPortMap().
m_peakSystemDeviceIndex()
unsigned int udevanalyserforpeak_ns::UdevAnalyserForPeak::m_peakSystemDeviceIndex (std::string s) private
get the global device index "0" pcan-usb_pro_fd/0/can0 pcan-usb_pro_fd/devid=9054 pcan32 pcanusbpfd32
Definition at line 271 of file UdevAnalyserForPeak.cpp.
Referenced by m_createUdevPortMap().
peakExtendedIdentifierToSocketCanDevice()
std::string udevanalyserforpeak_ns::UdevAnalyserForPeak::peakExtendedIdentifierToSocketCanDevice (std::string extPortId) static
convert a PEAK extended portIdentifier to a socketcan device, i.e. "sock:can0:device123456" -> "can2"
meaning
input: PEAK_device_t.localCanPort = 0 PEAK_device_t.deviceID = 123456
returns: "can2"
This means that the PEAK can bridge with deviceID 123456 is currently the second device in the socketcan sequence, and that we talk to the first port (locally "can0") of that device. Since the first device has (obviously) 2 can ports (globally "can0", "can1") we end up with globally "can2" which is the next in the sequence. Why do we need this? With peak bridges the socketcan device sequence depends on the USB plugin events and is therefore not deterministic. Strictly speaking on has no guarantee that "can2" [second bridge, first port] talks to the same electronics on every day, on monday it might also talk to the firs device. This stems from the fact that the peak driver does NOT publish the device ID under linux, therefore the udev system can't pick it up to provide deterministic mapping either. The fix is (1) stamp a unique deviceID into the bridge using peak tools under windows. this value is persistent and will survive a reboot. (2) under linux, use an extended peak port identifier : "sock:can0:device123456". CanModule remaps ports under the hood for you (3) under windows, use the brief port identifier "sock:can2" as before. If you use an extended port identifier the world will explode. But you can't, anyway, since socketcan is linux only. The peak driver for windows is better: it (seems to) take care of the device ID properly, BUT DONT ASK ME for that crap...
Definition at line 67 of file UdevAnalyserForPeak.cpp.
References getInstance(), m_logItHandleSock, and m_peak_v.
Referenced by CSockCanScan::configureCanBoard().
showMap()
void udevanalyserforpeak_ns::UdevAnalyserForPeak::showMap () static
Definition at line 118 of file UdevAnalyserForPeak.cpp.
References m_logItHandleSock, and m_peak_v.
Referenced by CSockCanScan::configureCanBoard().
Member Data Documentation
m_instance_ptr
UdevAnalyserForPeak * udevanalyserforpeak_ns::UdevAnalyserForPeak::m_instance_ptr = 0 static private
Definition at line 49 of file UdevAnalyserForPeak.h.
Referenced by getInstance().
m_logItHandleSock
Log::LogComponentHandle udevanalyserforpeak_ns::UdevAnalyserForPeak::m_logItHandleSock = 0 static private
Definition at line 55 of file UdevAnalyserForPeak.h.
Referenced by m_createUdevPortMap(), peakExtendedIdentifierToSocketCanDevice(), showMap(), and UdevAnalyserForPeak().
m_peak_v
std::vector< UdevAnalyserForPeak::PEAK_device_t > udevanalyserforpeak_ns::UdevAnalyserForPeak::m_peak_v static private
Definition at line 52 of file UdevAnalyserForPeak.h.
Referenced by m_createUdevPortMap(), m_peakDeviceIdFromSystemDeviceIndex(), peakExtendedIdentifierToSocketCanDevice(), and showMap().
The documentation for this class was generated from the following files:
CanInterfaceImplementations/sockcan/UdevAnalyserForPeak.h
CanInterfaceImplementations/sockcan/UdevAnalyserForPeak.cpp