CanModule: CanModule::CanLibLoaderLin Class Reference
CanModule::CanLibLoaderLin Class Reference
#include <CanLibLoaderLin.h>
Public Member Functions
CanLibLoaderLin (const std::string &libName)
virtual ~CanLibLoaderLin ()
Public Member Functions inherited from CanModule::CanLibLoader
virtual ~CanLibLoader ()
SHARED_LIB_EXPORT_DEFN CanModule::CCanAccess * openCanBus (std::string name, std::string parameters)
SHARED_LIB_EXPORT_DEFN void closeCanBus (CanModule::CCanAccess *cca)
void setLibName (std::string ln)
std::string getLibName ()
Protected Member Functions
virtual void dynamicallyLoadLib (const std::string &libName)
virtual CCanAccess * createCanAccess ()
Protected Member Functions inherited from CanModule::CanLibLoader
CanLibLoader (const std::string &libName)
Private Attributes
void * p_dynamicLibrary
Additional Inherited Members
Static Public Member Functions inherited from CanModule::CanLibLoader
static SHARED_LIB_EXPORT_DEFN CanLibLoader * createInstance (const std::string &libName)
Public Attributes inherited from CanModule::CanLibLoader
Log::LogComponentHandle lh
Detailed Description
Definition at line 28 of file CanLibLoaderLin.h.
Constructor & Destructor Documentation
CanLibLoaderLin()
CanModule::CanLibLoaderLin::CanLibLoaderLin (const std::string & libName)
Definition at line 38 of file CanLibLoaderLin.cpp.
References dynamicallyLoadLib(), and CanModule::CanLibLoader::lh.
~CanLibLoaderLin()
CanModule::CanLibLoaderLin::~CanLibLoaderLin () virtual
Definition at line 46 of file CanLibLoaderLin.cpp.
References p_dynamicLibrary.
Member Function Documentation
createCanAccess()
CCanAccess * CanModule::CanLibLoaderLin::createCanAccess () protected virtual
Once the library is loaded, resolve the function getHalAccess, which will give us an instance of the wanted object: "access" One access instance corresponds to one CAN port (and whatever is needed on the computer side: ethernet, USB, whatnot)
Implements CanModule::CanLibLoader.
Definition at line 77 of file CanLibLoaderLin.cpp.
References CanModule::CanLibLoader::lh, and p_dynamicLibrary.
dynamicallyLoadLib()
void CanModule::CanLibLoaderLin::dynamicallyLoadLib (const std::string & libName) protected virtual
Implements CanModule::CanLibLoader.
Definition at line 50 of file CanLibLoaderLin.cpp.
References CanModule::CanLibLoader::lh, p_dynamicLibrary, and CanModule::CanLibLoader::setLibName().
Referenced by CanLibLoaderLin().
Member Data Documentation
p_dynamicLibrary
void* CanModule::CanLibLoaderLin::p_dynamicLibrary private
Definition at line 43 of file CanLibLoaderLin.h.
Referenced by createCanAccess(), dynamicallyLoadLib(), and ~CanLibLoaderLin().
The documentation for this class was generated from the following files:
CanLibLoader/include/CanLibLoaderLin.h
CanLibLoader/src/CanLibLoaderLin.cpp