CanModule: AnaCanScan Class Reference
AnaCanScan Class Reference
#include <AnaCanScan.h>
Classes
struct ANAGATE_PORTDEF_t
Public Member Functions
AnaCanScan ()
AnaCanScan (AnaCanScan const &other)=delete
AnaCanScan & operator= (AnaCanScan const &other)=delete
virtual ~AnaCanScan ()
virtual int createBus (const std::string name, const std::string parameters)
virtual bool sendMessage (short cobID, unsigned char len, unsigned char *message, bool rtr=false)
virtual bool sendMessage (CanMessage *)
virtual bool sendRemoteRequest (short cobID)
virtual void getStatistics (CanStatistics &result)
void statisticsOnRecieve (int)
void callbackOnRecieve (CanMessage &)
uint32_t getPortStatus ()
virtual uint32_t getPortBitrate ()
virtual void setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action)
virtual void setReconnectReceptionTimeout (unsigned int timeout)
virtual void setReconnectFailedSendCount (unsigned int c)
virtual CanModule::ReconnectAutoCondition getReconnectCondition ()
virtual CanModule::ReconnectAction getReconnectAction ()
virtual void stopBus (void)
Public Member Functions inherited from CanModule::CCanAccess
CCanAccess ()
std::string & getBusName ()
virtual ~CCanAccess ()
bool initialiseLogging (LogItInstance *remoteInstance)
LogItInstance * getLogItInstance ()
std::vector< std::string > parseNameAndParameters (std::string name, std::string parameters)
void triggerReconnectionThread ()
void waitForReconnectionThreadTrigger ()
void decreaseSendFailedCountdown ()
void resetSendFailedCountdown ()
Private Member Functions
AnaInt32 reconnectThisPort ()
void CanReconnectionThread ()
bool sendAnErrorMessage (AnaInt32 status)
std::string ipAdress ()
int canPortNumber ()
int handle ()
int configureCanBoard (const std::string name, const std::string parameters)
int connectReceptionHandler ()
int openCanPort ()
int reconnect ()
const char * errorCodeToString (long error)
void eraseReceptionHandlerFromMap (AnaInt32 h)
std::string ana_canGetErrorText (long errorCode)
Static Private Member Functions
static void showAnaCanScanObjectMap ()
static int reconnectAllPorts (std::string ip)
static void addCanHandleOfPortIp (AnaInt32 handle, int port, std::string ip)
static void deleteCanHandleOfPortIp (int port, std::string ip)
static AnaInt32 getCanHandleOfPortIp (int port, std::string ip)
static void setIpReconnectInProgress (std::string ip, bool flag)
static bool isIpReconnectInProgress (std::string ip)
Private Attributes
int m_canPortNumber
std::string m_canIPAddress
unsigned int m_baudRate
DWORD m_idCanScanThread
bool m_canCloseDevice
std::string m_busName
std::string m_busParameters
AnaInt32 m_UcanHandle
CanStatistics m_statistics
AnaInt32 m_timeout
bool m_busStopped
Static Private Attributes
static Log::LogComponentHandle st_logItHandleAnagate = 0
static std::map< int, ANAGATE_PORTDEF_t > st_canHandleMap
static std::map< std::string, bool > m_reconnectInProgress_map
Additional Inherited Members
Static Public Member Functions inherited from CanModule::CCanAccess
static std::string reconnectConditionString (CanModule::ReconnectAutoCondition c)
static std::string reconnectActionString (CanModule::ReconnectAction c)
Public Attributes inherited from CanModule::CCanAccess
boost::signals2::signal< void(const CanMessage &) > canMessageCame
boost::signals2::signal< void(const int, const char *, timeval &) > canMessageError
Protected Member Functions inherited from CanModule::CCanAccess
bool hasTimeoutOnReception ()
void resetTimeoutOnReception ()
void resetTimeNow ()
Protected Attributes inherited from CanModule::CCanAccess
std::string m_sBusName
CanParameters m_CanParameters
CanModule::ReconnectAutoCondition m_reconnectCondition
CanModule::ReconnectAction m_reconnectAction
std::atomic_uint m_timeoutOnReception
std::atomic_int m_failedSendCountdown
std::atomic_uint m_maxFailedSendCount
std::thread * m_hCanReconnectionThread
std::atomic_bool m_reconnectTrigger
std::mutex m_reconnection_mtx
std::condition_variable m_reconnection_cv
Detailed Description
one CAN port on an anagate bridge, an anagate bridge is an ip number. There are (physical) bridges with several ip numbers: we treat them as separated modules.
Definition at line 74 of file AnaCanScan.h.
Constructor & Destructor Documentation
AnaCanScan() [1/2]
AnaCanScan::AnaCanScan ()
start a reconnection thread
Definition at line 55 of file AnaCanScan.cpp.
References CanModule::CanStatistics::beginNewRun(), CanReconnectionThread(), CanModule::CCanAccess::m_failedSendCountdown, CanModule::CCanAccess::m_hCanReconnectionThread, CanModule::CCanAccess::m_maxFailedSendCount, m_statistics, and CanModule::CanStatistics::setTimeSinceOpened().
AnaCanScan() [2/2]
AnaCanScan::AnaCanScan (AnaCanScan const & other) delete
~AnaCanScan()
AnaCanScan::~AnaCanScan () virtual
Shut down can scan thread
Definition at line 98 of file AnaCanScan.cpp.
References MLOGANA, and stopBus().
Member Function Documentation
addCanHandleOfPortIp()
void AnaCanScan::addCanHandleOfPortIp (AnaInt32 handle, int port, std::string ip) static private
add a can handle into the map if it does not yet exist
Definition at line 358 of file AnaCanScan.cpp.
References handle(), AnaCanScan::ANAGATE_PORTDEF_t::ip, AnaCanScan::ANAGATE_PORTDEF_t::port, st_canHandleMap, and st_logItHandleAnagate.
Referenced by openCanPort(), and reconnect().
ana_canGetErrorText()
std::string AnaCanScan::ana_canGetErrorText (long errorCode) private
give back the error message fro the code, from appendixA
Definition at line 991 of file AnaCanScan.cpp.
References ANA_ERR_INVALID_CONF, ANA_ERR_INVALID_CONF_DATA, ANA_ERR_INVALID_CRC, ANA_ERR_INVALID_DEVICE_HANDLE, ANA_ERR_INVALID_DEVICE_TYPE, ANA_ERR_NONE, ANA_ERR_OP_CMD_FAILED, ANA_ERR_OPEN_MAX_CONN, ANA_ERR_TCPIP_CALLNOTALLOWED, ANA_ERR_TCPIP_NOT_INITIALIZED, ANA_ERR_TCPIP_NOTCONNECTED, ANA_ERR_TCPIP_SOCKET, and ANA_ERR_TCPIP_TIMEOUT.
callbackOnRecieve()
void AnaCanScan::callbackOnRecieve (CanMessage & msg)
callback API: sends a boost signal with payload
Definition at line 201 of file AnaCanScan.cpp.
References CanModule::CCanAccess::canMessageCame, CanModule::CCanAccess::m_reconnectCondition, and CanModule::CCanAccess::resetTimeoutOnReception().
canPortNumber()
int AnaCanScan::canPortNumber () inline private
Definition at line 156 of file AnaCanScan.h.
CanReconnectionThread()
void AnaCanScan::CanReconnectionThread () private
Reconnection thread managing the reconnection behavior, per port. The behavior settings can not change during runtime. This thread is initialized after the main thread is up, and then listens on its cond.var as a trigger. Triggers occur in two contexts: sending and receiving problems. If there is a sending problem which lasts for a while (usually) the reconnection thread will be also triggered for each failed sending: the thread will be "hammered" by triggers. ince the reconnection takes some time, many triggers will be lost. That is in fact a desired behavior.
The parameters are all atomics for increased thread-safety, even though the documentation about the predicate is unclear on that point. Since atomics just provide a "sequential memory layout" for the variables to prevent race conditions they are good to use for this but the code still has to be threadsafe and reentrant... ;-) Doesn't eat anything anyway on that small scale with scalars only.
https://en.cppreference.com/w/cpp/thread/condition_variable/wait
lets check the timeoutOnReception reconnect condition. If it is true, all we can do is to close/open the socket again since the underlying hardware is hidden by socketcan abstraction. Like his we do not have to pollute the "sendMessage" like for anagate, and that is cleaner.
just manage the conditions, and continue/skip if there is nothing to do
anagate (physical) modules can have more than one ethernet RJ45. we treat each ip address as "one bridge" in this context
CanModule::ReconnectAction::allBusesOnBridge
Definition at line 1038 of file AnaCanScan.cpp.
References CanModule::allBusesOnBridge, CanModule::CCanAccess::getBusName(), getReconnectAction(), getReconnectCondition(), ipAdress(), m_canIPAddress, CanModule::CCanAccess::m_failedSendCountdown, CanModule::CCanAccess::m_reconnectAction, CanModule::CCanAccess::m_reconnectCondition, MLOGANA, CanModule::never, CanModule::CCanAccess::reconnectActionString(), reconnectAllPorts(), CanModule::CCanAccess::reconnectConditionString(), reconnectThisPort(), CanModule::CCanAccess::resetSendFailedCountdown(), CanModule::CCanAccess::resetTimeoutOnReception(), CanModule::sendFail, showAnaCanScanObjectMap(), CanModule::singleBus, CanModule::timeoutOnReception, and CanModule::CCanAccess::waitForReconnectionThreadTrigger().
Referenced by AnaCanScan().
configureCanBoard()
int AnaCanScan::configureCanBoard (const std::string name, const std::string parameters) private
decode the name, parameter and return the port of the configured module i.e. name="an:0:128.141.159.194" i.e. parameters= "p0 p1 p2 p3 p4 p5 p6" with i.e. "125000 0 1 0 0 0 6000" p0=baudrate p1= operation mode p2 = termination p3 = high speed flag p4 = time stamp p5 = sync mode p6 = timeout/ms
Definition at line 278 of file AnaCanScan.cpp.
References m_baudRate, m_canIPAddress, CanModule::CCanAccess::m_CanParameters, m_canPortNumber, CanModule::CanParameters::m_iHighSpeed, CanModule::CanParameters::m_iNumberOfDetectedParameters, CanModule::CanParameters::m_iOperationMode, CanModule::CanParameters::m_iSyncMode, CanModule::CanParameters::m_iTermination, CanModule::CanParameters::m_iTimeout, CanModule::CanParameters::m_iTimeStamp, CanModule::CanParameters::m_lBaudRate, m_timeout, MLOGANA, openCanPort(), and CanModule::CCanAccess::parseNameAndParameters().
Referenced by createBus().
connectReceptionHandler()
AnaInt32 AnaCanScan::connectReceptionHandler () private
connect the reception handler and only AFTER that register the handle in the global obj. map, since reception is asynchron. Finally, in the caller, the stale handle is deleted from the map.
Definition at line 786 of file AnaCanScan.cpp.
References g_AnaCanScanObjectMap, InternalCallback(), m_canIPAddress, CanModule::CCanAccess::m_CanParameters, m_canPortNumber, CanModule::CanParameters::m_iHighSpeed, CanModule::CanParameters::m_iOperationMode, CanModule::CanParameters::m_iTermination, CanModule::CanParameters::m_iTimeStamp, CanModule::CanParameters::m_lBaudRate, m_UcanHandle, and MLOGANA.
Referenced by reconnectThisPort().
createBus()
int AnaCanScan::createBus (const std::string name, const std::string parameters) virtual
Method that initialises a CAN bus channel for anagate. All following methods called on the same object will be using this initialized channel.
Parameters
name 3 parameters separated by ":" like "n0:n1:n2" n0 = "an" for anagate n1 = port number on the module, 0=A, 1=B, etc etc n2 = ip number ex.: "an:can1:137.138.12.99" speaks to port B (=1) on anagate module at the ip ex.: "an:1:137.138.12.99" works as well
parameters up to 5 parameters separated by whitespaces : "p0 p1 p2 p3 p4" in THAT order, positive integers
"Unspecified" (or empty): using defaults = "125000 0 0 0 0" // all params missing
p0: bitrate: 10000, 20000, 50000, 62000, 100000, 125000, 250000, 500000, 800000, 1000000 bit/s
p1: operatingMode: 0=default mode, values 1 (loop back) and 2 (listen) are not supported by CanModule
p2: termination: 0=not terminated (default), 1=terminated (120 Ohm for CAN bus)
p3: highSpeed: 0=deactivated (default), 1=activated. If activated, confirmation and filtering of CAN traffic are switched off for baud rates > 125000 this flag is needed, and it is set automatically for you if you forgot it (WRN)
p4: TimeStamp: 0=deactivated (default), 1=activated. If activated, a timestamp is added to the CAN frame. Not all modules support this. i.e. "250000 0 1 0 0" (see anagate manual for more details)
Returns
0: new bus, OK, add it please 1: existing bus, OK, do not add -1: error
Implements CanModule::CCanAccess.
Definition at line 236 of file AnaCanScan.cpp.
References configureCanBoard(), CanModule::LogItComponentName, m_busName, m_busParameters, m_busStopped, MLOGANA, and st_logItHandleAnagate.
deleteCanHandleOfPortIp()
void AnaCanScan::deleteCanHandleOfPortIp (int port, std::string ip) static private
find and erase a map entry handle->{port, ip} todo: mutex protect, work on copy
Definition at line 376 of file AnaCanScan.cpp.
References handle(), AnaCanScan::ANAGATE_PORTDEF_t::ip, AnaCanScan::ANAGATE_PORTDEF_t::port, st_canHandleMap, and st_logItHandleAnagate.
Referenced by reconnect(), and stopBus().
eraseReceptionHandlerFromMap()
void AnaCanScan::eraseReceptionHandlerFromMap (AnaInt32 h) private
todo: protect with mutex, work on copy
Definition at line 837 of file AnaCanScan.cpp.
References g_AnaCanScanObjectMap, m_busName, and MLOGANA.
Referenced by stopBus().
errorCodeToString()
const char* AnaCanScan::errorCodeToString (long error) inline private
Definition at line 162 of file AnaCanScan.h.
Referenced by sendAnErrorMessage().
getCanHandleOfPortIp()
AnaInt32 AnaCanScan::getCanHandleOfPortIp (int port, std::string ip) static private
find the handle from port, ip we have to search through the whole map to know
Definition at line 401 of file AnaCanScan.cpp.
References st_canHandleMap, and st_logItHandleAnagate.
Referenced by openCanPort().
getPortBitrate()
virtual uint32_t AnaCanScan::getPortBitrate () inline virtual
returns the bitrate of that port [bits/sec] according to what CanModule buffers say. This is the setting used for setting up the hardware, after any default rules have been applied, but BEFORE any vendor specific encoding into obscure bitpatterns occurs. This happens at port opening and the bitrate can only be changed at that moment. So please call this method just after you have opened the port. But also since there is no hw interaction and it just returns a buffer, you may call it as often as you like.
Implements CanModule::CCanAccess.
Definition at line 93 of file AnaCanScan.h.
getPortStatus()
uint32_t AnaCanScan::getPortStatus () virtual
CANCanDeviceConnectState , translate from counter 1 = DISCONNECTED : 2 = CONNECTING : 3 = CONNECTED 4 = DISCONNECTING 5 = NOT_INITIALIZED b3...b27: unused
into simple bitpattern (counter) 0, 10, 11, 100, 101
Implements CanModule::CCanAccess.
Definition at line 90 of file AnaCanScan.cpp.
References CANMODULE_STATUS_BP_ANAGATE, and m_UcanHandle.
getReconnectAction()
virtual CanModule::ReconnectAction AnaCanScan::getReconnectAction () inline virtual
read back the r.action
Implements CanModule::CCanAccess.
Definition at line 102 of file AnaCanScan.h.
Referenced by CanReconnectionThread().
getReconnectCondition()
virtual CanModule::ReconnectAutoCondition AnaCanScan::getReconnectCondition () inline virtual
read back the r.condition
Implements CanModule::CCanAccess.
Definition at line 101 of file AnaCanScan.h.
Referenced by CanReconnectionThread(), and sendMessage().
getStatistics()
void AnaCanScan::getStatistics (CanStatistics & result) virtual
Implements CanModule::CCanAccess.
Definition at line 1018 of file AnaCanScan.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CanStatistics::computeDerived(), m_baudRate, and m_statistics.
handle()
int AnaCanScan::handle () inline private
Definition at line 157 of file AnaCanScan.h.
Referenced by addCanHandleOfPortIp(), and deleteCanHandleOfPortIp().
ipAdress()
std::string AnaCanScan::ipAdress () inline private
Definition at line 155 of file AnaCanScan.h.
Referenced by CanReconnectionThread().
isIpReconnectInProgress()
bool AnaCanScan::isIpReconnectInProgress (std::string ip) static private
checks if a reconnection is already in progress for the bridge at that IP. Several ports can (and will) fail at the same time, but the bridge should be reset only once, and not again for each port.
Definition at line 138 of file AnaCanScan.cpp.
References m_reconnectInProgress_map.
Referenced by reconnectAllPorts().
openCanPort()
int AnaCanScan::openCanPort () private
Obtains an Anagate canport and opens it. The name of the port and parameters should have been specified by preceding call to configureCanboard()
Returns
less than zero in case of error, otherwise success
communicate with the hardware using the CanOpen interface: open anagate port, attach reply handler. No message queuing. CANSetMaxSizePerQueue not called==default==0
check if that anagate bridge (ip) is already initialized, if not we create it.
Definition at line 424 of file AnaCanScan.cpp.
References addCanHandleOfPortIp(), g_AnaCanScanObjectMap, getCanHandleOfPortIp(), InternalCallback(), m_canIPAddress, CanModule::CCanAccess::m_CanParameters, m_canPortNumber, CanModule::CanParameters::m_iHighSpeed, CanModule::CanParameters::m_iOperationMode, CanModule::CanParameters::m_iTermination, CanModule::CanParameters::m_iTimeStamp, CanModule::CanParameters::m_lBaudRate, m_timeout, m_UcanHandle, and MLOGANA.
Referenced by configureCanBoard().
operator=()
AnaCanScan& AnaCanScan::operator= (AnaCanScan const & other) delete
reconnect()
int AnaCanScan::reconnect () private
we try to reconnect one port after a power loss, and we should do this for all ports returns: 0 = OK -1 = could not CANOpenDevice device -2 = could not connect callback CANSetCallbackEx -3 = device was found open, tried to close but did not succeed (maybe you should just try sending again)
1 = DISCONNECTED : The connection to the AnaGate is disconnected. 2 = CONNECTING : The connection is connecting. 3 = CONNECTED : The connection is established. 4 = DISCONNECTING : The connection is disonnecting. 5 = NOT_INITIALIZED : The network protocol is not successfully initialized.
Definition at line 856 of file AnaCanScan.cpp.
References addCanHandleOfPortIp(), deleteCanHandleOfPortIp(), m_canCloseDevice, m_canIPAddress, m_canPortNumber, m_timeout, m_UcanHandle, and MLOGANA.
Referenced by reconnectThisPort().
reconnectAllPorts()
AnaInt32 AnaCanScan::reconnectAllPorts (std::string ip) static private
reconnects all opened ports of a given ip address=one module. We have one object per CAN port, so i.e. for an anagate duo (ports A and B) we have two objects with the same IP but with port 0 and 1.So we will have to scan over all objects there because we do not know how many CANports a given anagate bridge has. We also allow globally only one ongoing reconnect to one ip at a time. Theoretically we could have a separate reconnection thread per ip, but that looks like overcomplicating the code and the issue. If several anagate modules fail they will all reconnect one after the other. That is OK since if all of these modules loose power and reboot at the same moment they will also be ready at roughly the same moment for reconnect. That means that we have to wait for the first ip to reconnect for a while but then all other ips will reconnect rather quickly in the most likely case. returns: 0 = OK -1 = cant open / reconnect CAN ports +1 = ignore, since another thread is doing the reconnect already
delete the map elements where the key is different from the handle, since we reassigned handles in the living objects like: g_AnaCanScanPointerMap[ m_UcanHandle ] = this;
Definition at line 673 of file AnaCanScan.cpp.
References anagateReconnectMutex, g_AnaCanScanObjectMap, isIpReconnectInProgress(), setIpReconnectInProgress(), showAnaCanScanObjectMap(), and st_logItHandleAnagate.
Referenced by CanReconnectionThread().
reconnectThisPort()
AnaInt32 AnaCanScan::reconnectThisPort () private
only reconnect this object's port and make dure the callback map entry is updated as well
delete the map elements where the key is different from the handle, since we reassigned handles in the living objects like: g_AnaCanScanPointerMap[ m_UcanHandle ] = this;
Definition at line 621 of file AnaCanScan.cpp.
References connectReceptionHandler(), g_AnaCanScanObjectMap, m_canIPAddress, m_canPortNumber, MLOGANA, reconnect(), showAnaCanScanObjectMap(), and st_logItHandleAnagate.
Referenced by CanReconnectionThread().
sendAnErrorMessage()
bool AnaCanScan::sendAnErrorMessage (AnaInt32 status) private
if sending had a problem invoke the error handler with a message. Ultimately, this sends a boost::signal to a connected boost::slot in the client's code.
Definition at line 502 of file AnaCanScan.cpp.
References CanModule::CCanAccess::canMessageError, and errorCodeToString().
Referenced by sendMessage(), and sendRemoteRequest().
sendMessage() [1/2]
bool AnaCanScan::sendMessage (CanMessage * canm) virtual
Reimplemented from CanModule::CCanAccess.
Definition at line 964 of file AnaCanScan.cpp.
References CanMsgStruct::c_data, CanMsgStruct::c_dlc, CanMsgStruct::c_id, CanMsgStruct::c_rtr, and sendMessage().
sendMessage() [2/2]
bool AnaCanScan::sendMessage (short cobID, unsigned char len, unsigned char * message, bool rtr = false) virtual
send a CAN message frame (8 byte) for anagate Method that sends a message through the can bus channel. If the method createBus was not called before this, sendMessage will fail, as there is no can bus channel to send a message trough.
Parameters
cobID Identifier that will be used for the message.
len Length of the message. If the message is bigger than 8 characters, it will be split into separate 8 characters messages.
message Message to be sent trough the can bus.
rtr is the message a remote transmission request?
Returns
Was the sending process successful?
before sending the message we check if the reception timeout has not been overrun. Because this would entail some reconnection action, and in that case we skip the send on that bus. we invoke the thread only if the timeout has already occurred, and so we do not need to check the timeout in the thread anymore.
we can send now
Implements CanModule::CCanAccess.
Definition at line 528 of file AnaCanScan.cpp.
References CanModule::canMessage2ToString(), CanModule::CCanAccess::decreaseSendFailedCountdown(), CanModule::CCanAccess::getBusName(), getReconnectCondition(), CanModule::CCanAccess::hasTimeoutOnReception(), m_busStopped, m_canCloseDevice, m_canIPAddress, m_canPortNumber, CanModule::CCanAccess::m_reconnectCondition, m_statistics, m_UcanHandle, MLOGANA, CanModule::CanStatistics::onTransmit(), CanModule::CCanAccess::reconnectConditionString(), sendAnErrorMessage(), CanModule::CanStatistics::setTimeSinceTransmitted(), CanModule::timeoutOnReception, and CanModule::CCanAccess::triggerReconnectionThread().
Referenced by sendMessage().
sendRemoteRequest()
bool AnaCanScan::sendRemoteRequest (short cobID) virtual
Method that sends a remote request trough the can bus channel. If the method createBus was not called before this, sendMessage will fail, as there is no can bus channel to send the request trough. Similar to sendMessage, but it sends an special message reserved for requests.
Parameters
cobID Identifier that will be used for the request.
Returns
Was the initialisation process successful?
Implements CanModule::CCanAccess.
Definition at line 976 of file AnaCanScan.cpp.
References m_UcanHandle, MLOGANA, and sendAnErrorMessage().
setIpReconnectInProgress()
void AnaCanScan::setIpReconnectInProgress (std::string ip, bool flag) static private
Definition at line 117 of file AnaCanScan.cpp.
References m_reconnectInProgress_map.
Referenced by reconnectAllPorts().
setReconnectBehavior()
virtual void AnaCanScan::setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action) inline virtual
configuring the reconnection behavior: a condition triggers an action. The implementation is implementation-specific because not all vendor APIs permit the same behavior: not all combinations are available for all vendors/implementations. The implemented reconnection behavior is standardized nevertheless: "you get what you see". Foe each CanBus you have to choose one condition and one action. Condition detection and action execution are then automatic inside CanModule.
Parameters
CanModule::ReconnectAutoCondition cond
sendFail (default): a reconnection is triggered automatically if a send on the canBus fails. The number of failed sends can be set (default is 10). The failed sending must be strictly consecutive, if there is a succeeded sending, the internal counting restarts.
timeoutOnReception: the last time of a successful reception on a given channel can be monitored. If the last reception is older than 120 sec a reset is triggered automatically. This last successful reception time is calculated each time a send is invoked. The timeout is specified in seconds, default is 120sec.
never: this condition is always false and therefore no automatic reconnection action will be triggered. You can still call the explicit method reconnect(<action>) but it is up to the client (server) to decide when.
CanModule::ReconnectAction action
singleBus (default): a single connection (canbus, channel) is reset and reception handler is reconnected.
wholeBridge if available, the whole bridge is reset, affecting all physical channels on that bridge. Only available for anagate. If a bridge is shared between multiple tasks, all channels across tasks are reset, affecting all tasks connected to that bridge. Evidently, a given channel must only be used by at most one task.
Implements CanModule::CCanAccess.
Definition at line 95 of file AnaCanScan.h.
setReconnectFailedSendCount()
virtual void AnaCanScan::setReconnectFailedSendCount (unsigned int c) inline virtual
set the counter for failed consecutive sending attempts, for reconnection. default is 10.
Implements CanModule::CCanAccess.
Definition at line 100 of file AnaCanScan.h.
setReconnectReceptionTimeout()
virtual void AnaCanScan::setReconnectReceptionTimeout (unsigned int timeout) inline virtual
set the timout interval for message reception, for the reconnection behaviour. Units is seconds, default is 120.
Implements CanModule::CCanAccess.
Definition at line 99 of file AnaCanScan.h.
showAnaCanScanObjectMap()
void AnaCanScan::showAnaCanScanObjectMap () static private
display the handle->object map, and using the object, show more details
Definition at line 603 of file AnaCanScan.cpp.
References g_AnaCanScanObjectMap, and st_logItHandleAnagate.
Referenced by CanReconnectionThread(), reconnectAllPorts(), and reconnectThisPort().
statisticsOnRecieve()
void AnaCanScan::statisticsOnRecieve (int bytes)
update statistics API
Definition at line 192 of file AnaCanScan.cpp.
References m_statistics, CanModule::CanStatistics::onReceive(), and CanModule::CanStatistics::setTimeSinceReceived().
stopBus()
void AnaCanScan::stopBus (void) virtual
force implementation
Implements CanModule::CCanAccess.
Definition at line 104 of file AnaCanScan.cpp.
References deleteCanHandleOfPortIp(), eraseReceptionHandlerFromMap(), m_busName, m_busStopped, m_canIPAddress, m_canPortNumber, m_UcanHandle, and MLOGANA.
Referenced by ~AnaCanScan().
Member Data Documentation
m_baudRate
unsigned int AnaCanScan::m_baudRate private
Definition at line 109 of file AnaCanScan.h.
Referenced by configureCanBoard(), and getStatistics().
m_busName
std::string AnaCanScan::m_busName private
Definition at line 112 of file AnaCanScan.h.
Referenced by createBus(), eraseReceptionHandlerFromMap(), and stopBus().
m_busParameters
std::string AnaCanScan::m_busParameters private
Definition at line 113 of file AnaCanScan.h.
Referenced by createBus().
m_busStopped
bool AnaCanScan::m_busStopped private
Definition at line 117 of file AnaCanScan.h.
Referenced by createBus(), sendMessage(), and stopBus().
m_canCloseDevice
bool AnaCanScan::m_canCloseDevice private
Definition at line 111 of file AnaCanScan.h.
Referenced by reconnect(), and sendMessage().
m_canIPAddress
std::string AnaCanScan::m_canIPAddress private
Definition at line 108 of file AnaCanScan.h.
Referenced by CanReconnectionThread(), configureCanBoard(), connectReceptionHandler(), openCanPort(), reconnect(), reconnectThisPort(), sendMessage(), and stopBus().
m_canPortNumber
int AnaCanScan::m_canPortNumber private
Definition at line 107 of file AnaCanScan.h.
Referenced by configureCanBoard(), connectReceptionHandler(), openCanPort(), reconnect(), reconnectThisPort(), sendMessage(), and stopBus().
m_idCanScanThread
DWORD AnaCanScan::m_idCanScanThread private
Definition at line 110 of file AnaCanScan.h.
m_reconnectInProgress_map
std::map< std::string, bool > AnaCanScan::m_reconnectInProgress_map static private
Definition at line 150 of file AnaCanScan.h.
Referenced by isIpReconnectInProgress(), and setIpReconnectInProgress().
m_statistics
CanStatistics AnaCanScan::m_statistics private
Definition at line 115 of file AnaCanScan.h.
Referenced by AnaCanScan(), getStatistics(), sendMessage(), and statisticsOnRecieve().
m_timeout
AnaInt32 AnaCanScan::m_timeout private
Definition at line 116 of file AnaCanScan.h.
Referenced by configureCanBoard(), openCanPort(), and reconnect().
m_UcanHandle
AnaInt32 AnaCanScan::m_UcanHandle private
Definition at line 114 of file AnaCanScan.h.
Referenced by connectReceptionHandler(), getPortStatus(), openCanPort(), reconnect(), sendMessage(), sendRemoteRequest(), and stopBus().
st_canHandleMap
std::map< int, AnaCanScan::ANAGATE_PORTDEF_t > AnaCanScan::st_canHandleMap static private
Definition at line 142 of file AnaCanScan.h.
Referenced by addCanHandleOfPortIp(), deleteCanHandleOfPortIp(), and getCanHandleOfPortIp().
st_logItHandleAnagate
Log::LogComponentHandle AnaCanScan::st_logItHandleAnagate = 0 static private
we would like to keep logging from a few static methods as well, since one IP number corresponds to many ports and some class-level management is going on for the connect-reconnect behavior. We definitely need these to be static. So since we need the logit handle static there is no point in having it also private. At least the cross-thread references to the handler are within this class only. It is all re-entrant code, and the handler does not change during runtime any more, so no mutex protection for now.
Definition at line 129 of file AnaCanScan.h.
Referenced by addCanHandleOfPortIp(), createBus(), deleteCanHandleOfPortIp(), getCanHandleOfPortIp(), reconnectAllPorts(), reconnectThisPort(), and showAnaCanScanObjectMap().
The documentation for this class was generated from the following files:
CanInterfaceImplementations/anagate/AnaCanScan.h
CanInterfaceImplementations/anagate/AnaCanScan.cpp