CanModule: CanModule::CanLibLoaderWin Class Reference
CanModule::CanLibLoaderWin Class Reference
#include <CanLibLoaderWin.h>
Public Member Functions
void ErrorExit (LPTSTR lpszFunction)
CanLibLoaderWin (const std::string &libName)
virtual ~CanLibLoaderWin ()
Public Member Functions inherited from CanModule::CanLibLoader
virtual ~CanLibLoader ()
SHARED_LIB_EXPORT_DEFN CanModule::CCanAccess * openCanBus (std::string name, std::string parameters)
SHARED_LIB_EXPORT_DEFN void closeCanBus (CanModule::CCanAccess *cca)
void setLibName (std::string ln)
std::string getLibName ()
Protected Member Functions
virtual void dynamicallyLoadLib (const std::string &libName)
virtual CCanAccess * createCanAccess ()
Protected Member Functions inherited from CanModule::CanLibLoader
CanLibLoader (const std::string &libName)
Private Attributes
HMODULE m_pDynamicLibrary
Additional Inherited Members
Static Public Member Functions inherited from CanModule::CanLibLoader
static SHARED_LIB_EXPORT_DEFN CanLibLoader * createInstance (const std::string &libName)
Public Attributes inherited from CanModule::CanLibLoader
Log::LogComponentHandle lh
Detailed Description
Definition at line 33 of file CanLibLoaderWin.h.
Constructor & Destructor Documentation
CanLibLoaderWin()
CanModule::CanLibLoaderWin::CanLibLoaderWin (const std::string & libName)
Definition at line 69 of file CanLibLoaderWin.cpp.
References dynamicallyLoadLib(), and CanModule::CanLibLoader::lh.
~CanLibLoaderWin()
CanModule::CanLibLoaderWin::~CanLibLoaderWin () virtual
Definition at line 76 of file CanLibLoaderWin.cpp.
References m_pDynamicLibrary.
Member Function Documentation
createCanAccess()
CanModule::CCanAccess * CanModule::CanLibLoaderWin::createCanAccess () protected virtual
Once the library is loaded, resolve the function getHalAccess, which will give us an instance of the wanted object: "access" One access instance corresponds to one CAN port (and whatever is needed on the computer side: ethernet, USB, whatnot)
Implements CanModule::CanLibLoader.
Definition at line 121 of file CanLibLoaderWin.cpp.
References CanModule::CanLibLoader::lh, and m_pDynamicLibrary.
dynamicallyLoadLib()
void CanModule::CanLibLoaderWin::dynamicallyLoadLib (const std::string & libName) protected virtual
The dll is loaded trough LoadLibrary (Windows API) but error reporting is poor. Use extended API method for this to get around the signing at least. ===AnaGate libs are NOT INSTALLED on the system, so make sure the vendor libs in question are in the search path: copy them to the bin exec dir. ===Systec libs are in fact installed into the system C:\Windows\system32\USBCAN64.dll or so, so for systec nothing has to be done. In fact this is unclean, but that is what they deliver.
Implements CanModule::CanLibLoader.
Definition at line 88 of file CanLibLoaderWin.cpp.
References ErrorExit(), CanModule::CanLibLoader::lh, m_pDynamicLibrary, and CanModule::CanLibLoader::setLibName().
Referenced by CanLibLoaderWin().
ErrorExit()
void CanModule::CanLibLoaderWin::ErrorExit (LPTSTR lpszFunction)
Retrieve the system error message for the last-error code this seems to return error code 0 even if lib pointer is NULL
Definition at line 38 of file CanLibLoaderWin.cpp.
Referenced by dynamicallyLoadLib().
Member Data Documentation
m_pDynamicLibrary
HMODULE CanModule::CanLibLoaderWin::m_pDynamicLibrary private
Definition at line 50 of file CanLibLoaderWin.h.
Referenced by createCanAccess(), dynamicallyLoadLib(), and ~CanLibLoaderWin().
The documentation for this class was generated from the following files:
CanLibLoader/include/CanLibLoaderWin.h
CanLibLoader/src/CanLibLoaderWin.cpp