CanModule: CSockCanScan Class Reference
CSockCanScan Class Reference
#include <SockCanScan.h>
Public Member Functions
CSockCanScan ()
CSockCanScan (CSockCanScan const &other)=delete
CSockCanScan & operator= (CSockCanScan const &other)=delete
virtual ~CSockCanScan ()
virtual bool sendRemoteRequest (short cobID)
virtual int createBus (const string name, string parameters)
virtual bool sendMessage (short cobID, unsigned char len, unsigned char *message, bool rtr=false)
virtual void getStatistics (CanStatistics &result)
virtual uint32_t getPortStatus ()
virtual uint32_t getPortBitrate ()
int getHandler ()
Log::LogComponentHandle logItHandle ()
virtual void setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action)
virtual void setReconnectReceptionTimeout (unsigned int timeout)
virtual void setReconnectFailedSendCount (unsigned int c)
virtual CanModule::ReconnectAutoCondition getReconnectCondition ()
virtual CanModule::ReconnectAction getReconnectAction ()
virtual void stopBus ()
Public Member Functions inherited from CanModule::CCanAccess
CCanAccess ()
virtual bool sendMessage (CanMessage *canm)
std::string & getBusName ()
virtual ~CCanAccess ()
bool initialiseLogging (LogItInstance *remoteInstance)
LogItInstance * getLogItInstance ()
vector< string > parseNameAndParameters (string name, string parameters)
void triggerReconnectionThread ()
void waitForReconnectionThreadTrigger ()
void decreaseSendFailedCountdown ()
void resetSendFailedCountdown ()
Static Public Member Functions
static can_frame emptyCanFrame (void)
Static Public Attributes
static std::map< string, string > m_busMap
Private Member Functions
void updateInitialError ()
void sendErrorMessage (const char *)
void clearErrorMessage ()
int configureCanBoard (const string name, const string parameters)
void updateBusStatus ()
int openCanPort ()
void CanScanControlThread ()
void CanReconnectionThread ()
Static Private Member Functions
static std::string errorFrameToString (const struct can_frame &f)
Private Attributes
volatile atomic_bool m_CanScanThreadRunEnableFlag
atomic_int m_sock
int m_errorCode
CanStatistics m_statistics
std::thread * m_hCanScanThread
std::string m_channelName
std::string m_busName
Log::LogComponentHandle m_logItHandleSock
Additional Inherited Members
Public Attributes inherited from CanModule::CCanAccess
boost::signals2::signal< void(const CanMessage &) > canMessageCame
boost::signals2::signal< void(const int, const char *, timeval &) > canMessageError
Protected Member Functions inherited from CanModule::CCanAccess
bool hasTimeoutOnReception ()
void resetTimeoutOnReception ()
void resetTimeNow ()
Static Protected Member Functions inherited from CanModule::CCanAccess
static std::string reconnectConditionString (CanModule::ReconnectAutoCondition c)
static std::string reconnectActionString (CanModule::ReconnectAction c)
Protected Attributes inherited from CanModule::CCanAccess
string m_sBusName
CanParameters m_CanParameters
CanModule::ReconnectAutoCondition m_reconnectCondition
CanModule::ReconnectAction m_reconnectAction
atomic_uint m_timeoutOnReception
atomic_int m_failedSendCountdown
atomic_uint m_maxFailedSendCount
std::thread * m_hCanReconnectionThread
atomic_bool m_reconnectTrigger
std::mutex m_reconnection_mtx
std::condition_variable m_reconnection_cv
Detailed Description
Definition at line 46 of file SockCanScan.h.
Constructor & Destructor Documentation
CSockCanScan() [1/2]
CSockCanScan::CSockCanScan ()
Definition at line 67 of file SockCanScan.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CCanAccess::m_failedSendCountdown, CanModule::CCanAccess::m_maxFailedSendCount, m_statistics, and CanModule::CanStatistics::setTimeSinceOpened().
CSockCanScan() [2/2]
CSockCanScan::CSockCanScan (CSockCanScan const & other) delete
~CSockCanScan()
CSockCanScan::~CSockCanScan () virtual
Definition at line 488 of file SockCanScan.cpp.
References MLOGSOCK, and stopBus().
Member Function Documentation
CanReconnectionThread()
void CSockCanScan::CanReconnectionThread () private
reconnection behavior thread, always up
Reconnection thread managing the reconnection behavior, per port. The behavior settings can not change during runtime. This thread is initialized after the main thread is up, and then listens on its cond.var as a trigger. Triggers occur in two contexts: sending and receiving problems. If there is a sending problem which lasts for a while (usually) the reconnection thread will be also triggered for each failed sending: the thread will be "hammered" by triggers. ince the reconnection takes some time, many triggers will be lost. That is in fact a desired behavior.
The parameters are all atomics for increased thread-safety, even though the documentation about the predicate is unclear on that point. Since atomics just provide a "sequential memory layout" for the variables to prevent race conditions they are good to use for this but the code still has to be threadsafe and reentrant... ;-) Doesn't eat anything anyway on that small scale with scalars only.
https://en.cppreference.com/w/cpp/thread/condition_variable/wait
lets check the timeoutOnReception reconnect condition. If it is true, all we can do is to close/open the socket again since the underlying hardware is hidden by socketcan abstraction. Like his we do not have to pollute the "sendMessage" like for anagate, and that is cleaner.
we get triggered all the time, essentially with reception timeouts, but also sometimes with a send fail. we need to manage the conditions since the triggering is identical, no parameters are transmitted, the predicate is just a boolean to keep it simple.
... or the reception timed out: we did not receive anything on the bus for a certain time (not: count). That is a somewhat dangerous condition but it can be extremely useful if you know what you do.
socketcan abstracts away the notion of a "module", and that is the point. Various plugin-orders should lead to the same device mapping nevertheless. But then we can't refer to a module and reset all of it's channels easily in linux. Unless we make a big effort and keep track of which port is on which module, for peak: more udev calls, for systec: we need to read the module serial number or similar. Maybe there is an elegant way out, but I think it is not worth it. Use a PDU if you want to reset your systec16. For peak the notion of "module" is already difficult through socketcan (udev calls needed to identify the modules) and peak bridges get their power over USB. So in fact testing peak means "rebooting" unless you want to unplug the USB. Therefore "allBusesOnBridge" as reconnect action is not available for sock.
CanModule::ReconnectAction::allBusesOnBridge is not implemented for sock
Definition at line 369 of file SockCanScan.cpp.
References CanModule::CCanAccess::getBusName(), getReconnectAction(), getReconnectCondition(), CanModule::CCanAccess::hasTimeoutOnReception(), CanModule::CCanAccess::m_failedSendCountdown, CanModule::CCanAccess::m_reconnectAction, CanModule::CCanAccess::m_reconnectCondition, m_sock, MLOGSOCK, CanModule::never, openCanPort(), CanModule::CCanAccess::reconnectActionString(), CanModule::CCanAccess::reconnectConditionString(), CanModule::CCanAccess::resetSendFailedCountdown(), CanModule::CCanAccess::resetTimeoutOnReception(), CanModule::sendFail, CanModule::singleBus, CanModule::timeoutOnReception, and CanModule::CCanAccess::waitForReconnectionThreadTrigger().
Referenced by createBus().
CanScanControlThread()
void CSockCanScan::CanScanControlThread () private
The main control thread function for the CAN update scan manager: a private non-static method, which is called on the object (this) following std::thread C++11 ways.
reading from socket, and supervising thread for monitoring the sockets/CAN buses. It takes an object reference (cast) and listens with a select call on that socket/object. The select runs with 1Hz, and if there is nothing to receive it should timeout.
the select failed. that is very bad, system problem, but let's continue nevertheless. There is not much we can do
select returned, either on the timeout or with something on that socket/object. Assumption: at this moment sock holds meaningful value. Now select result >=0 so it was either nothing received (timeout) or something received
The preceding call took either 'timeout' time, or there is frame received – perfect time to attempt to clean error frame.
select reports that it has got something, so no timeout in this case
try to re-open the socket. only reopen the socket if we still need it. If we need to shutdown the thread, leave it closed and terminate main loop.
if we have an open socket again, and we can read numberOfReadBytes >=0 we should be fine again and continue the thread execution normally
we have a CAN message, error free, lets digest it
OPCUA-2607. Lets just stop filtering them out. This is only done here anyway, all other vendor implementations don't care.
reformat and buffer the message from the socket. this actually should exclude more bits
the select got nothing to read, this was just a timeout, all is fine. Unless the reconnect timeout has something to do.
the reconnect behavior happens in an extra thread so that the sendMessage becomes non blocking. This is the reception of the message part, and strictly speaking we could do the reconnection due to reception message timeout also here. For cleanliness, lets use that extra reconnection thread nevertheless here.
that reconnection thread is always up and it depends on three private variables: the socket, the ReconnectAutoCondition and the ReconnectAction. It is done in a pretty stupid way so that is is fast, for all vendors: you just trigger it whenever and it checks itself what to do.
Definition at line 103 of file SockCanScan.cpp.
References MLOGSOCK.
Referenced by createBus().
clearErrorMessage()
void CSockCanScan::clearErrorMessage () private
Definition at line 1037 of file SockCanScan.cpp.
References CanModule::CCanAccess::canMessageError, m_sock, and MLOGSOCK.
Referenced by updateInitialError().
configureCanBoard()
int CSockCanScan::configureCanBoard (const string name, const string parameters) private
for PEAK bridges, we have a problem: the local ports are not mapped to the global socketcan ports in a deterministic way. OPCUA-1735. So, lets make a udev call here, analyze the result and manipulate the port number so that it becomes a global port number.
In order to distinguish between systec (where it works) and peak bridges we use an extended name: systec: name="sock:can0" peak: name="sock:can0:device17440"
now, we manipulate the lname to reflect the absolute port which we found out. We do the rewiring at initialisation, like this we don't care anymore during runtime.
Definition at line 494 of file SockCanScan.cpp.
References m_channelName, m_logItHandleSock, MLOGSOCK, openCanPort(), CanModule::CCanAccess::parseNameAndParameters(), udevanalyserforpeak_ns::UdevAnalyserForPeak::peakExtendedIdentifierToSocketCanDevice(), and udevanalyserforpeak_ns::UdevAnalyserForPeak::showMap().
Referenced by createBus().
createBus()
int CSockCanScan::createBus (const string name, string parameters) virtual
Method that initializes a can bus channel. The following methods called upon the same object will be using this initialized channel.
Parameters
name = 2 parameters separated by ":", like "n0:n1"
n0 = "sock" for sockets linux, used by systec and peak
n1 = CAN port number on the module, can be prefixed with "can"
ex.: "sock:can1" speaks to port 1 on systec or peak module
ex.: "sock:1" works as well
parameters one parameter: "p0", positive integer
"Unspecified" (or empty): using defaults = "125000" // params missing
p0: bitrate: 50000, 100000, 125000, 250000, 500000, 1000000 bit/s, other values might be allowed by the module
i.e. "250000"
Returns
Was the initialization process successful?
dont create a main thread for the same bus twice: if it exists already, just configure the board again this protects agains having multiple threads if a given port ports is opened several times: protects against erro/unusual runtime. If the connection is closed, it's main thread is stopped and joined, and the port is erased from the connection map. when the same port is opened again later on, a (new) main thread is created, and the connection is again added to the map.
start a reconnection thread
Implements CanModule::CCanAccess.
Definition at line 897 of file SockCanScan.cpp.
References CanReconnectionThread(), CanScanControlThread(), configureCanBoard(), CanModule::LogItComponentName, m_busMap, m_busName, m_CanScanThreadRunEnableFlag, CanModule::CCanAccess::m_hCanReconnectionThread, m_hCanScanThread, m_logItHandleSock, m_sock, MLOGSOCK, and sockReconnectMutex.
emptyCanFrame()
static can_frame CSockCanScan::emptyCanFrame (void) inline static
produce and empty can frame
Definition at line 89 of file SockCanScan.h.
Referenced by sendMessage().
errorFrameToString()
std::string CSockCanScan::errorFrameToString (const struct can_frame & f) static private
Transforms an error frame into an error message (string format)
Definition at line 963 of file SockCanScan.cpp.
getHandler()
int CSockCanScan::getHandler () inline
Returns socket handler
Definition at line 84 of file SockCanScan.h.
getPortBitrate()
virtual uint32_t CSockCanScan::getPortBitrate () inline virtual
returns the bitrate of that port [bits/sec] according to what CanModule buffers say. This is the setting used for setting up the hardware, after any default rules have been applied, but BEFORE any vendor specific encoding into obscure bitpatterns occurs. This happens at port opening and the bitrate can only be changed at that moment. So please call this method just after you have opened the port. But also since there is no hw interaction and it just returns a buffer, you may call it as often as you like. Default bitrate is always 125000bits/s if "Unspecified"
Implements CanModule::CCanAccess.
Definition at line 79 of file SockCanScan.h.
getPortStatus()
virtual uint32_t CSockCanScan::getPortStatus () inline virtual
return socketcan port status as-is, from can_netlink.h enum can_state { CAN_STATE_ERROR_ACTIVE = 0, RX/TX error count < 96 CAN_STATE_ERROR_WARNING, RX/TX error count < 128 CAN_STATE_ERROR_PASSIVE, RX/TX error count < 256 CAN_STATE_BUS_OFF, RX/TX error count >= 256 CAN_STATE_STOPPED, Device is stopped CAN_STATE_SLEEPING, Device is sleeping CAN_STATE_MAX };
Implements CanModule::CCanAccess.
Definition at line 73 of file SockCanScan.h.
References CANMODULE_STATUS_BP_SOCK, and CanModule::CanStatistics::portStatus().
getReconnectAction()
virtual CanModule::ReconnectAction CSockCanScan::getReconnectAction () inline virtual
read back the r.action
Implements CanModule::CCanAccess.
Definition at line 111 of file SockCanScan.h.
Referenced by CanReconnectionThread().
getReconnectCondition()
virtual CanModule::ReconnectAutoCondition CSockCanScan::getReconnectCondition () inline virtual
read back the r.condition
Implements CanModule::CCanAccess.
Definition at line 110 of file SockCanScan.h.
Referenced by CanReconnectionThread().
getStatistics()
void CSockCanScan::getStatistics (CanStatistics & result) virtual
Implements CanModule::CCanAccess.
Definition at line 1080 of file SockCanScan.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CanStatistics::computeDerived(), CanModule::CanStatistics::encodeCanModuleStatus(), CanModule::CCanAccess::m_CanParameters, CanModule::CanParameters::m_lBaudRate, and m_statistics.
logItHandle()
Log::LogComponentHandle CSockCanScan::logItHandle () inline
Definition at line 99 of file SockCanScan.h.
openCanPort()
int CSockCanScan::openCanPort () private
Obtains a SocketCAN socket and opens it. The name of the port and parameters should have been specified by preceding call to configureCanboard()
Returns
less than zero in case of error, otherwise success
stop, set bitrate, start a CAN port, open a socket for it, set the socket to CAN, bind it and check any errors
Definition at line 535 of file SockCanScan.cpp.
References CanModule::CanModuleerrnoToString(), CanModule::CCanAccess::m_CanParameters, m_channelName, CanModule::CanParameters::m_dontReconfigure, m_errorCode, CanModule::CanParameters::m_lBaudRate, m_sock, m_statistics, MLOG, MLOGSOCK, CanModule::CanStatistics::setTimeSinceOpened(), and updateInitialError().
Referenced by CanReconnectionThread(), and configureCanBoard().
operator=()
CSockCanScan& CSockCanScan::operator= (CSockCanScan const & other) delete
sendErrorMessage()
void CSockCanScan::sendErrorMessage (const char * mess) private
Definition at line 1046 of file SockCanScan.cpp.
References CanModule::CCanAccess::canMessageError, m_sock, and MLOGSOCK.
sendMessage()
bool CSockCanScan::sendMessage (short cobID, unsigned char len, unsigned char * message, bool rtr = false) virtual
Method that sends a message trough the can bus channel. If the method createBUS was not called before this, sendMessage will fail, as there is no can bus channel to send a message through.
Parameters
cobID Identifier that will be used for the message.
len Length of the message. If the message is bigger than 8 characters, it will be split into separate 8 characters messages.
message Message to be sent trough the can bus.
rtr is the message a remote transmission request?
Returns
Was the initialisation process successful?
OPCUA-2604: sendMessage must be non blocking. The reconnection behavior therefore must be managed in a separate thread.
returns: true for success, otherwise false
Implements CanModule::CCanAccess.
Definition at line 691 of file SockCanScan.cpp.
References emptyCanFrame(), m_CanScanThreadRunEnableFlag, m_sock, and MLOGSOCK.
sendRemoteRequest()
bool CSockCanScan::sendRemoteRequest (short cobID) virtual
Method that sends a remote request trough the can bus channel. If the method createBUS was not called before this, sendMessage will fail, as there is no can bus channel to send the request trough. Similar to sendMessage, but it sends an special message reserved for requests.
Parameters
cobID Identifier that will be used for the request.
Returns
: Was the initialisation process successful?
that is not tested or used until now, and I am not sure it works
Implements CanModule::CCanAccess.
Definition at line 831 of file SockCanScan.cpp.
References CanModule::CanModuleerrnoToString(), m_sock, m_statistics, MLOGSOCK, and CanModule::CanStatistics::setTimeSinceReceived().
setReconnectBehavior()
virtual void CSockCanScan::setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action) inline virtual
configuring the reconnection behavior: a condition triggers an action. The implementation is implementation-specific because not all vendor APIs permit the same behavior: not all combinations are available for all vendors/implementations. The implemented reconnection behavior is standardized nevertheless: "you get what you see". Foe each CanBus you have to choose one condition and one action. Condition detection and action execution are then automatic inside CanModule.
Parameters
CanModule::ReconnectAutoCondition cond
sendFail (default): a reconnection is triggered automatically if a send on the canBus fails. The number of failed sends can be set (default is 10). The failed sending must be strictly consecutive, if there is a succeeded sending, the internal counting restarts.
timeoutOnReception: the last time of a successful reception on a given channel can be monitored. If the last reception is older than 120 sec a reset is triggered automatically. This last successful reception time is calculated each time a send is invoked. The timeout is specified in seconds, default is 120sec.
never: this condition is always false and therefore no automatic reconnection action will be triggered. You can still call the explicit method reconnect(<action>) but it is up to the client (server) to decide when.
CanModule::ReconnectAction action
singleBus (default): a single connection (canbus, channel) is reset and reception handler is reconnected.
wholeBridge if available, the whole bridge is reset, affecting all physical channels on that bridge. Only available for anagate. If a bridge is shared between multiple tasks, all channels across tasks are reset, affecting all tasks connected to that bridge. Evidently, a given channel must only be used by at most one task.
Implements CanModule::CCanAccess.
Definition at line 101 of file SockCanScan.h.
setReconnectFailedSendCount()
virtual void CSockCanScan::setReconnectFailedSendCount (unsigned int c) inline virtual
set the counter for failed consecutive sending attempts, for reconnection. default is 10.
Implements CanModule::CCanAccess.
Definition at line 106 of file SockCanScan.h.
setReconnectReceptionTimeout()
virtual void CSockCanScan::setReconnectReceptionTimeout (unsigned int timeout) inline virtual
set the timout interval for message reception, for the reconnection behaviour. Units is seconds, default is 120.
Implements CanModule::CCanAccess.
Definition at line 105 of file SockCanScan.h.
stopBus()
void CSockCanScan::stopBus () virtual
notify the main thread to finish and delete the bus from the map of connections
Implements CanModule::CCanAccess.
Definition at line 1057 of file SockCanScan.cpp.
References m_busMap, m_busName, m_CanScanThreadRunEnableFlag, m_hCanScanThread, MLOGSOCK, and sockReconnectMutex.
Referenced by ~CSockCanScan().
updateBusStatus()
void CSockCanScan::updateBusStatus () private
update the CAN bus status IFLA from socketcan and make up a CanModule status bitpattern out from this. Each vendor has to implement this with the same bit meanings.
Errors are a subset of status.
std::string CSockCanScan::errorFrameToString(const struct can_frame &canFrame) fabricates a string, we need a bitpattern
int can_get_restart_ms(const char *name, __u32 *restart_ms); int can_get_bittiming(const char *name, struct can_bittiming *bt); int can_get_ctrlmode(const char *name, struct can_ctrlmode *cm); int can_get_state(const char *name, int *state); int can_get_clock(const char *name, struct can_clock *clock); int can_get_bittiming_const(const char *name, struct can_bittiming_const *btc); int can_get_berr_counter(const char *name, struct can_berr_counter *bc); int can_get_device_stats(const char *name, struct can_device_stats *cds);
Definition at line 633 of file SockCanScan.cpp.
References m_channelName, m_statistics, and CanModule::CanStatistics::setPortStatus().
updateInitialError()
void CSockCanScan::updateInitialError () private
stop the supervisor thread using the flag and close the socket. Report an error when opening a can port
Definition at line 1089 of file SockCanScan.cpp.
References CanModule::CCanAccess::canMessageError, clearErrorMessage(), and m_errorCode.
Referenced by openCanPort().
Member Data Documentation
m_busMap
std::map< string, string > CSockCanScan::m_busMap static
Copyright CERN, 2015. All rights not expressly granted are reserved.
SockCanScan.cpp
Created on: Jul 21, 2011 Based on work by vfilimon Rework and logging done by Piotr Nikiel piotr.nosp@m.@nik.nosp@m.iel.i.nosp@m.nfo mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
Definition at line 98 of file SockCanScan.h.
Referenced by createBus(), and stopBus().
m_busName
std::string CSockCanScan::m_busName private
Definition at line 125 of file SockCanScan.h.
Referenced by createBus(), and stopBus().
m_CanScanThreadRunEnableFlag
volatile atomic_bool CSockCanScan::m_CanScanThreadRunEnableFlag private
Definition at line 116 of file SockCanScan.h.
Referenced by createBus(), sendMessage(), and stopBus().
m_channelName
std::string CSockCanScan::m_channelName private
Definition at line 124 of file SockCanScan.h.
Referenced by configureCanBoard(), openCanPort(), and updateBusStatus().
m_errorCode
int CSockCanScan::m_errorCode private
Definition at line 120 of file SockCanScan.h.
Referenced by openCanPort(), and updateInitialError().
m_hCanScanThread
std::thread* CSockCanScan::m_hCanScanThread private
Definition at line 123 of file SockCanScan.h.
Referenced by createBus(), and stopBus().
m_logItHandleSock
Log::LogComponentHandle CSockCanScan::m_logItHandleSock private
Definition at line 126 of file SockCanScan.h.
Referenced by configureCanBoard(), and createBus().
m_sock
atomic_int CSockCanScan::m_sock private
Definition at line 118 of file SockCanScan.h.
Referenced by CanReconnectionThread(), clearErrorMessage(), createBus(), openCanPort(), sendErrorMessage(), sendMessage(), and sendRemoteRequest().
m_statistics
CanStatistics CSockCanScan::m_statistics private
Definition at line 122 of file SockCanScan.h.
Referenced by CSockCanScan(), getStatistics(), openCanPort(), sendRemoteRequest(), and updateBusStatus().
The documentation for this class was generated from the following files:
CanInterfaceImplementations/sockcan/SockCanScan.h
CanInterfaceImplementations/sockcan/SockCanScan.cpp