CanModule: MockCanAccess Class Reference
MockCanAccess Class Reference
#include <MockCanAccess.h>
Public Member Functions
MockCanAccess ()
virtual ~MockCanAccess ()
MockCanAccess (MockCanAccess const &other)=delete
MockCanAccess & operator= (MockCanAccess const &other)=delete
virtual int createBus (const string name, const string parameters)
virtual bool sendRemoteRequest (short cobID)
virtual bool sendMessage (short cobID, unsigned char len, unsigned char *message, bool rtr=false)
virtual void getStatistics (CanModule::CanStatistics &result)
virtual bool initialiseLogging (LogItInstance *remoteInstance)
virtual void setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action)
virtual void setReconnectReceptionTimeout (unsigned int timeout)
virtual void setReconnectFailedSendCount (unsigned int c)
virtual CanModule::ReconnectAutoCondition getReconnectCondition ()
virtual CanModule::ReconnectAction getReconnectAction ()
virtual uint32_t getPortStatus ()
virtual uint32_t getPortBitrate ()
Public Member Functions inherited from CanModule::CCanAccess
CCanAccess ()
virtual bool sendMessage (CanMessage *canm)
std::string & getBusName ()
virtual ~CCanAccess ()
bool initialiseLogging (LogItInstance *remoteInstance)
LogItInstance * getLogItInstance ()
vector< string > parseNameAndParameters (string name, string parameters)
Static Public Member Functions
static std::string getCanMessageDataAsString (const unsigned char *data, const unsigned char &len=8)
Private Attributes
CanModule::CanStatistics m_statistics
unsigned int m_baudRate
Static Private Attributes
static int st_CCanAccess_icount
Additional Inherited Members
Public Attributes inherited from CanModule::CCanAccess
boost::signals2::signal< void(const CanMessage &) > canMessageCame
boost::signals2::signal< void(const int, const char *, timeval &) > canMessageError
Protected Member Functions inherited from CanModule::CCanAccess
bool hasTimeoutOnReception ()
void resetTimeoutOnReception ()
void resetTimeNow ()
Static Protected Member Functions inherited from CanModule::CCanAccess
static std::string reconnectConditionString (CanModule::ReconnectAutoCondition c)
static std::string reconnectActionString (CanModule::ReconnectAction c)
Protected Attributes inherited from CanModule::CCanAccess
string m_sBusName
CanParameters m_CanParameters
CanModule::ReconnectAutoCondition m_reconnectCondition
CanModule::ReconnectAction m_reconnectAction
unsigned int m_timeoutOnReception
int m_triggerCounter
unsigned int m_failedSendCounter
Detailed Description
Definition at line 32 of file MockCanAccess.h.
Constructor & Destructor Documentation
MockCanAccess() [1/2]
MockCanAccess::MockCanAccess ()
Definition at line 30 of file MockCanAccess.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CCanAccess::m_failedSendCounter, m_statistics, CanModule::CCanAccess::m_triggerCounter, and CanModule::CanStatistics::setTimeSinceOpened().
~MockCanAccess()
MockCanAccess::~MockCanAccess () virtual
Definition at line 38 of file MockCanAccess.cpp.
MockCanAccess() [2/2]
MockCanAccess::MockCanAccess (MockCanAccess const & other) delete
Member Function Documentation
createBus()
int MockCanAccess::createBus (const string name, const string parameters) virtual
Method that initialises a can bus channel. The following methods called upon the same object will be using this initialised channel.
Parameters
name Name of the can bus channel. The specific mapping will change depending on the interface used. For example, accessing channel 0 for the systec interface would be using name "st:9", while in socket can the same channel would be "sock:can0". anagate interface would be an:192.168.1.2 for the default ip address
parameters Different parameters used for the initialisation. For using the default parameters just set this to "Unspecified" anagate: pass the ip number
Returns
: init OK, bus was created = OK = 0 init OK, bus was skipped because it exists already = 1 init failed = -1
Implements CanModule::CCanAccess.
Definition at line 43 of file MockCanAccess.cpp.
getCanMessageDataAsString()
std::string MockCanAccess::getCanMessageDataAsString (const unsigned char * data, const unsigned char & len = 8) static
Definition at line 80 of file MockCanAccess.cpp.
getPortBitrate()
virtual uint32_t MockCanAccess::getPortBitrate () inline virtual
returns the bitrate of that port [bits/sec] according to what CanModule buffers say. This is the setting used for setting up the hardware, after any default rules have been applied, but BEFORE any vendor specific encoding into obscure bitpatterns occurs. This happens at port opening and the bitrate can only be changed at that moment. So please call this method just after you have opened the port. But also since there is no hw interaction and it just returns a buffer, you may call it as often as you like. Default bitrate is always 125000bits/s if "Unspecified"
Implements CanModule::CCanAccess.
Definition at line 59 of file MockCanAccess.h.
getPortStatus()
virtual uint32_t MockCanAccess::getPortStatus () inline virtual
according to vendor and OS, acquire bus status, and return one uint32_t bitpattern which has the same rules for all vendors. In fact the status for vendors is too different to be abstracted into a common bitpattern.
the implementation occupies the highest nibble, and it is a counter (see CANMODULE_STATUS_BP_SOCK etc)
0x1<<28 = sock (linux)
0x2<<28 = anagate (linux, windows)
0x3<<28 = peak (windows)
0x4<<28 = systec (windows)
0x5<<28....0xf<<28 = unused, for future use
the **specific status** occupies bits b0..b27, and it is a (composed) implementation specific bitpattern
Parameters
sock (linux): [ see can_netlink.h enum can_state ]
b0: 0x1 = CAN_STATE_ERROR_ACTIVE : RX/TX error count < 96
b1: 0x2 = CAN_STATE_ERROR_WARNING : RX/TX error count < 128
b2: 0x4 = CAN_STATE_ERROR_PASSIVE : RX/TX error count < 256
b3: 0x8 = CAN_STATE_BUS_OFF : RX/TX error count >= 256
b4: 0x10 = CAN_STATE_STOPPED : Device is stopped
b5: 0x20 = CAN_STATE_SLEEPING : Device is sleeping
b6...b27 unused
anagate (linux, windows): [ see CANDeviceConnectState ] CANCanDeviceConnectState , translate from counter (0 does not exists, thank you anagate)
1 = DISCONNECTED :
2 = CONNECTING :
3 = CONNECTED
4 = DISCONNECTING
5 = NOT_INITIALIZED
b3...b27: unused
I translate this into a simple bitpattern which is a counter : 000(does not occur), 001, 010, 011, 100, 101. Actually 011 means OK therefore. great.
peak (windows): see PCANBasic.h:113
#define PCAN_ERROR_OK 0x00000U // No error
#define PCAN_ERROR_XMTFULL 0x00001U // Transmit buffer in CAN controller is full
#define PCAN_ERROR_OVERRUN 0x00002U // CAN controller was read too late
#define PCAN_ERROR_BUSLIGHT 0x00004U // Bus error: an error counter reached the 'light' limit
#define PCAN_ERROR_BUSHEAVY 0x00008U // Bus error: an error counter reached the 'heavy' limit
#define PCAN_ERROR_BUSWARNING PCAN_ERROR_BUSHEAVY // Bus error: an error counter reached the 'warning' limit
#define PCAN_ERROR_BUSPASSIVE 0x40000U // Bus error: the CAN controller is error passive
#define PCAN_ERROR_BUSOFF 0x00010U // Bus error: the CAN controller is in bus-off state
#define PCAN_ERROR_ANYBUSERR (PCAN_ERROR_BUSWARNING | PCAN_ERROR_BUSLIGHT | PCAN_ERROR_BUSHEAVY | PCAN_ERROR_BUSOFF | PCAN_ERROR_BUSPASSIVE) // Mask for all bus errors
#define PCAN_ERROR_QRCVEMPTY 0x00020U // Receive queue is empty
#define PCAN_ERROR_QOVERRUN 0x00040U // Receive queue was read too late
#define PCAN_ERROR_QXMTFULL 0x00080U // Transmit queue is full
#define PCAN_ERROR_REGTEST 0x00100U // Test of the CAN controller hardware registers failed (no hardware found)
#define PCAN_ERROR_NODRIVER 0x00200U // Driver not loaded
#define PCAN_ERROR_HWINUSE 0x00400U // Hardware already in use by a Net
#define PCAN_ERROR_NETINUSE 0x00800U // A Client is already connected to the Net
#define PCAN_ERROR_ILLHW 0x01400U // Hardware handle is invalid
#define PCAN_ERROR_ILLNET 0x01800U // Net handle is invalid
#define PCAN_ERROR_ILLCLIENT 0x01C00U // Client handle is invalid
#define PCAN_ERROR_ILLHANDLE (PCAN_ERROR_ILLHW | PCAN_ERROR_ILLNET | PCAN_ERROR_ILLCLIENT) // Mask for all handle errors
#define PCAN_ERROR_RESOURCE 0x02000U // Resource (FIFO, Client, timeout) cannot be created
#define PCAN_ERROR_ILLPARAMTYPE 0x04000U // Invalid parameter
#define PCAN_ERROR_ILLPARAMVAL 0x08000U // Invalid parameter value
#define PCAN_ERROR_UNKNOWN 0x10000U // Unknown error
#define PCAN_ERROR_ILLDATA 0x20000U // Invalid data, function, or action
#define PCAN_ERROR_CAUTION 0x2000000U // An operation was successfully carried out, however, irregularities were registered
#define PCAN_ERROR_INITIALIZE 0x4000000U // Channel is not initialized [Value was changed from 0x40000 to 0x4000000]
#define PCAN_ERROR_ILLOPERATION 0x8000000U // Invalid operation [Value was changed from 0x80000 to 0x8000000]
systec (windows): [ see UcanGetStatus table19 (for CAN) and table20 (for USB) ]. This is a combination of socketcan bits and usb bits
b0: 0x1: tx overrun
b1: 0x2: rx overrun
b2: 0x4: error limit1 exceeded: warning limit
b3: 0x8: error limit2 exceeded: error passive
b4: 0x10: can controller is off
b5: unused
b6: 0x40: rx buffer overrun
b7: 0x80: tx buffer overrun
b8..b9: unused
b10: 0x400: transmit timeout, message dropped
b12..b11: unused
b13: 0x2000: module/usb got reset because of polling failure per second
b14: 0x4000: module/usb got reset because watchdog was not triggered
b15...b27: unused
Implements CanModule::CCanAccess.
Definition at line 58 of file MockCanAccess.h.
getReconnectAction()
virtual CanModule::ReconnectAction MockCanAccess::getReconnectAction () inline virtual
read back the r.action
Implements CanModule::CCanAccess.
Definition at line 57 of file MockCanAccess.h.
References CanModule::CCanAccess::m_reconnectAction.
getReconnectCondition()
virtual CanModule::ReconnectAutoCondition MockCanAccess::getReconnectCondition () inline virtual
read back the r.condition
Implements CanModule::CCanAccess.
Definition at line 56 of file MockCanAccess.h.
References CanModule::CCanAccess::m_reconnectCondition.
getStatistics()
void MockCanAccess::getStatistics (CanModule::CanStatistics & result) virtual
Implements CanModule::CCanAccess.
Definition at line 73 of file MockCanAccess.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CanStatistics::computeDerived(), m_baudRate, and m_statistics.
initialiseLogging()
bool MockCanAccess::initialiseLogging (LogItInstance * remoteInstance) virtual
Definition at line 85 of file MockCanAccess.cpp.
operator=()
MockCanAccess& MockCanAccess::operator= (MockCanAccess const & other) delete
sendMessage()
bool MockCanAccess::sendMessage (short cobID, unsigned char len, unsigned char * message, bool rtr = false) virtual
Method that sends a message through the can bus channel. If the method createBUS was not called before this, sendMessage will fail, as there is no can bus channel to send a message through.
Parameters
cobID Identifier that will be used for the message.
len Length of the message. If the message is bigger than 8 characters, it will be split into separate 8 characters messages.
message Message to be sent through the can bus.
rtr activate the Remote Transmission Request flag. Having this flag in a message with data/len is not part of the CAN standard, but since some hardware uses it anyway, the option to use it is provided.
Returns
: Was the initialisation process successful?
Implements CanModule::CCanAccess.
Definition at line 57 of file MockCanAccess.cpp.
References CanMsgStruct::c_data, CanMsgStruct::c_dlc, CanMsgStruct::c_id, CAN_ECHO_MSG, CanModule::CCanAccess::canMessageCame, m_statistics, and CanModule::CanStatistics::onTransmit().
sendRemoteRequest()
bool MockCanAccess::sendRemoteRequest (short cobID) virtual
Method that sends a remote request trough the can bus channel. If the method createBus was not called before this, sendMessage will fail, as there is no can bus channel to send the request trough. Similar to sendMessage, but it sends an special message reserved for requests.
Parameters
cobID Identifier that will be used for the request.
Returns
: Was the initialisation process successful?
Implements CanModule::CCanAccess.
Definition at line 50 of file MockCanAccess.cpp.
References m_statistics, and CanModule::CanStatistics::onTransmit().
setReconnectBehavior()
virtual void MockCanAccess::setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action) inline virtual
configuring the reconnection behavior: a condition triggers an action. The implementation is implementation-specific because not all vendor APIs permit the same behavior: not all combinations are available for all vendors/implementations. The implemented reconnection behavior is standardized nevertheless: "you get what you see". Foe each CanBus you have to choose one condition and one action. Condition detection and action execution are then automatic inside CanModule.
Parameters
CanModule::ReconnectAutoCondition cond
sendFail (default): a reconnection is triggered automatically if a send on the canBus fails. The number of failed sends can be set (default is 10). The failed sending must be strictly consecutive, if there is a succeeded sending, the internal counting restarts.
timeoutOnReception: the last time of a successful reception on a given channel can be monitored. If the last reception is older than 120 sec a reset is triggered automatically. This last successful reception time is calculated each time a send is invoked. The timeout is specified in seconds, default is 120sec.
never: this condition is always false and therefore no automatic reconnection action will be triggered. You can still call the explicit method reconnect(<action>) but it is up to the client (server) to decide when.
CanModule::ReconnectAction action
singleBus (default): a single connection (canbus, channel) is reset and reception handler is reconnected.
wholeBridge if available, the whole bridge is reset, affecting all physical channels on that bridge. Only available for anagate. If a bridge is shared between multiple tasks, all channels across tasks are reset, affecting all tasks connected to that bridge. Evidently, a given channel must only be used by at most one task.
hardReset: the bridge is reset in a "hard" way, i.e. firmware is rebooted (NOT reloaded or overwritten). Only available for anagate: the firmware of the bridge (ip) is reloaded using a special command of the anagate API which is not available through the common CanModule API, since it is vendor specific. This is a "hard software reset", and it is not the same as just power-cycling the module. It takes ~15secs and "is known to work nicely".
Implements CanModule::CCanAccess.
Definition at line 53 of file MockCanAccess.h.
setReconnectFailedSendCount()
virtual void MockCanAccess::setReconnectFailedSendCount (unsigned int c) inline virtual
set the counter for failed consecutive sending attempts, for reconnection. default is 10.
Implements CanModule::CCanAccess.
Definition at line 55 of file MockCanAccess.h.
References CanModule::CCanAccess::m_failedSendCounter, and CanModule::CCanAccess::m_triggerCounter.
setReconnectReceptionTimeout()
virtual void MockCanAccess::setReconnectReceptionTimeout (unsigned int timeout) inline virtual
set the timout interval for message reception, for the reconnection behaviour. Units is seconds, default is 120.
Implements CanModule::CCanAccess.
Definition at line 54 of file MockCanAccess.h.
References CanModule::CCanAccess::m_timeoutOnReception.
Member Data Documentation
m_baudRate
unsigned int MockCanAccess::m_baudRate private
Definition at line 66 of file MockCanAccess.h.
Referenced by getStatistics().
m_statistics
CanModule::CanStatistics MockCanAccess::m_statistics private
Definition at line 59 of file MockCanAccess.h.
Referenced by getStatistics(), MockCanAccess(), sendMessage(), and sendRemoteRequest().
st_CCanAccess_icount
int MockCanAccess::st_CCanAccess_icount static private
Definition at line 68 of file MockCanAccess.h.
The documentation for this class was generated from the following files:
CanInterfaceImplementations/unitTestMockUpImplementation/MockCanAccess.h
CanInterfaceImplementations/unitTestMockUpImplementation/MockCanAccess.cpp