CanModule: PKCanScan Class Reference
PKCanScan Class Reference
#include <pkcan.h>
Public Member Functions
PKCanScan ()
PKCanScan (PKCanScan const &other)=delete
PKCanScan & operator= (PKCanScan const &other)=delete
virtual ~PKCanScan ()
virtual int createBus (const std::string name, const std::string parameters)
virtual bool sendMessage (short cobID, unsigned char len, unsigned char *message, bool rtr=false)
virtual bool sendRemoteRequest (short cobID)
virtual void getStatistics (CanStatistics &result)
virtual uint32_t getPortStatus ()
virtual uint32_t getPortBitrate ()
bool getErrorMessage (long error, char **message)
Log::LogComponentHandle logItHandle ()
virtual void setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action)
virtual void setReconnectReceptionTimeout (unsigned int timeout)
virtual void setReconnectFailedSendCount (unsigned int c)
virtual CanModule::ReconnectAutoCondition getReconnectCondition ()
virtual CanModule::ReconnectAction getReconnectAction ()
virtual void stopBus ()
int getFailedSendCountdown ()
TPCANHandle getTPCANHandle ()
unsigned int getBaudRate ()
Public Member Functions inherited from CanModule::CCanAccess
CCanAccess ()
virtual bool sendMessage (CanMessage *canm)
std::string & getBusName ()
virtual ~CCanAccess ()
bool initialiseLogging (LogItInstance *remoteInstance)
LogItInstance * getLogItInstance ()
std::vector< std::string > parseNameAndParameters (std::string name, std::string parameters)
void triggerReconnectionThread ()
void waitForReconnectionThreadTrigger ()
void decreaseSendFailedCountdown ()
void resetSendFailedCountdown ()
Static Public Attributes
static std::map< std::string, std::string > m_busMap
Private Member Functions
TPCANHandle getHandle (const char *name)
bool sendErrorCode (long)
bool configureCanboard (const std::string name, const std::string parameters)
Static Private Member Functions
static DWORD WINAPI CanScanControlThread (LPVOID pCanScan)
static DWORD WINAPI CanReconnectionThread (LPVOID pCanScan)
Private Attributes
Log::LogComponentHandle m_logItHandlePk
CanStatistics m_statistics
TPCANStatus m_busStatus
bool m_CanScanThreadRunEnableFlag
unsigned int m_baudRate
std::string m_busName
std::string m_busParameters
TPCANHandle m_pkCanHandle
HANDLE m_hCanScanThread
HANDLE m_PeakReconnectionThread
DWORD m_idCanScanThread
DWORD m_idPeakReconnectionThread
Additional Inherited Members
Static Public Member Functions inherited from CanModule::CCanAccess
static std::string reconnectConditionString (CanModule::ReconnectAutoCondition c)
static std::string reconnectActionString (CanModule::ReconnectAction c)
Public Attributes inherited from CanModule::CCanAccess
boost::signals2::signal< void(const CanMessage &) > canMessageCame
boost::signals2::signal< void(const int, const char *, timeval &) > canMessageError
Protected Member Functions inherited from CanModule::CCanAccess
bool hasTimeoutOnReception ()
void resetTimeoutOnReception ()
void resetTimeNow ()
Protected Attributes inherited from CanModule::CCanAccess
std::string m_sBusName
CanParameters m_CanParameters
CanModule::ReconnectAutoCondition m_reconnectCondition
CanModule::ReconnectAction m_reconnectAction
std::atomic_uint m_timeoutOnReception
std::atomic_int m_failedSendCountdown
std::atomic_uint m_maxFailedSendCount
std::thread * m_hCanReconnectionThread
std::atomic_bool m_reconnectTrigger
std::mutex m_reconnection_mtx
std::condition_variable m_reconnection_cv
Detailed Description
Definition at line 38 of file pkcan.h.
Constructor & Destructor Documentation
PKCanScan() [1/2]
PKCanScan::PKCanScan ()
Definition at line 55 of file pkcan.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CCanAccess::m_failedSendCountdown, CanModule::CCanAccess::m_maxFailedSendCount, m_statistics, and CanModule::CanStatistics::setTimeSinceOpened().
PKCanScan() [2/2]
PKCanScan::PKCanScan (PKCanScan const & other) delete
~PKCanScan()
PKCanScan::~PKCanScan () virtual
Definition at line 70 of file pkcan.cpp.
References MLOGPK, and stopBus().
Member Function Documentation
CanReconnectionThread()
DWORD WINAPI PKCanScan::CanReconnectionThread (LPVOID pCanScan) static private
Reconnection thread managing the reconnection behavior, per port. The behavior settings can not change during runtime. This thread is initialized after the main thread is up, and then listens on its cond.var as a trigger. Triggers occur in two contexts: sending and receiving problems.
https://en.cppreference.com/w/cpp/thread/condition_variable/wait
Definition at line 572 of file pkcan.cpp.
References CanModule::allBusesOnBridge, getBaudRate(), getFailedSendCountdown(), getReconnectAction(), getReconnectCondition(), getTPCANHandle(), MLOGPK, CanModule::never, CanModule::CCanAccess::reconnectActionString(), CanModule::CCanAccess::reconnectConditionString(), CanModule::CCanAccess::resetSendFailedCountdown(), CanModule::CCanAccess::resetTimeoutOnReception(), CanModule::sendFail, CanModule::singleBus, CanModule::timeoutOnReception, and CanModule::CCanAccess::waitForReconnectionThreadTrigger().
Referenced by createBus().
CanScanControlThread()
DWORD WINAPI PKCanScan::CanScanControlThread (LPVOID pCanScan) static private
thread to supervise port activity
Definition at line 118 of file pkcan.cpp.
References CanMsgStruct::c_data, CanMsgStruct::c_dlc, CanMsgStruct::c_ff, CanMsgStruct::c_id, CanMsgStruct::c_time, CanModule::CCanAccess::canMessageCame, CanModule::canMessageToString(), CanModule::CCanAccess::getBusName(), getReconnectCondition(), CanModule::CCanAccess::hasTimeoutOnReception(), m_CanScanThreadRunEnableFlag, m_pkCanHandle, m_statistics, MLOGPK, CanModule::CanStatistics::onReceive(), CanModule::CCanAccess::resetTimeoutOnReception(), CanModule::CanStatistics::setTimeSinceReceived(), CanModule::timeoutOnReception, and CanModule::CCanAccess::triggerReconnectionThread().
Referenced by createBus().
configureCanboard()
bool PKCanScan::configureCanboard (const std::string name, const std::string parameters) private
method to configure peak modules. We restrict this to USB interfaces and fixed datarate (not FD) modules If needed this can relatively easily be extended to other interfaces and FD mods as well.
These USB CAN bridges are "plug&lplay CAN devices according to peak, so we can initialize them with only the handle and the baudrate. BUT - The handle is PER MODULE and not PER CHANNEL !!
Nevertheless this is called for each BUS creation.
returns: true = success false = failed
FD (flexible datarate) modules. we need to contruct (a complicated) bitrate string in this case, according to PEAK PCAN-Basic Documentation API manual p.82 two data rates, for nominal and data, can be defined. all these parameters have to be passed TPCANStatus tpcanStatus = CAN_InitializeFD(m_canObjHandler, m_baudRate); TPCANBitrateFD br = "f_clock_mhz=20, nom_brp=5, nom_tseg1=2, nom_tseg2=1, nom_sjw=1"; PCAN_BR_CLOCK_MHZ=20, PCAN_BR_NOM_BRP=5, PCAN_BR_DATA_TSEG1=2, PCAN_BR_DATA_TSEG2=1, PCAN_BR_NOM_SJW=1;
fixed datarate modules (classical CAN), plug and play we try 10 times until success, the OS is a bit slow
fixed data rate, non plug-and-play static TPCANStatus Initialize(TPCANHandle Channel, TPCANBaudrate Btr0Btr1, TPCANType HwType, UInt32 IOPort, UInt16 Interrupt);
Definition at line 271 of file pkcan.cpp.
References getHandle(), m_baudRate, CanModule::CCanAccess::m_CanParameters, CanModule::CanParameters::m_iNumberOfDetectedParameters, CanModule::CanParameters::m_lBaudRate, m_pkCanHandle, CanModule::CCanAccess::m_sBusName, MLOGPK, and CanModule::CCanAccess::parseNameAndParameters().
Referenced by createBus().
createBus()
int PKCanScan::createBus (const std::string name, const std::string parameters) virtual
Method that initialises a CAN bus channel for peak@windows (using PEAK Basic) All following methods called on the same object will be using this initialized channel. Only USB interfaces for PEAK modules, and only NON FD modules are supported for now.
Parameters
name = 2 parameters separated by ":" like "n0:n1"
n0 = "pk" for peak@windows
n1 = CAN port number on the module, can be prefixed with "can": 0..N
ex.: "pk:can1" speaks to port 1 (the second port) on peak module
ex.: "pk:1" works as well
parameters one parameter: "p0", positive integer
"Unspecified" (or empty): using defaults = "125000" // params missing
p0: bitrate: 50000, 100000, 125000, 250000, 500000, 1000000 bit/s i.e. "250000"
Returns
was the initialisation process successful: 0 = ok 1 = ok, bus exists already, we skip -1: not ok, problem configuring the board, try again -2: could not create the thread -3: sth else went wrong
start a reconnection thread
Implements CanModule::CCanAccess.
Definition at line 193 of file pkcan.cpp.
References CanReconnectionThread(), CanScanControlThread(), configureCanboard(), CanModule::LogItComponentName, m_busMap, m_busName, m_busParameters, m_hCanScanThread, m_idCanScanThread, m_idPeakReconnectionThread, m_logItHandlePk, m_PeakReconnectionThread, m_pkCanHandle, MLOGPK, and peakReconnectMutex.
getBaudRate()
unsigned int PKCanScan::getBaudRate () inline
Definition at line 90 of file pkcan.h.
Referenced by CanReconnectionThread().
getErrorMessage()
bool PKCanScan::getErrorMessage (long error, char ** message)
Definition at line 487 of file pkcan.cpp.
Referenced by sendErrorCode().
getFailedSendCountdown()
int PKCanScan::getFailedSendCountdown () inline
Definition at line 88 of file pkcan.h.
Referenced by CanReconnectionThread().
getHandle()
TPCANHandle PKCanScan::getHandle (const char * name) private
This method returns a TPCANHandle (which is in fact a specific vendor defined hex value) as a function of a human readable string. The human readable string basically codes the intefrace type (USB, ISA, PCI...) and the CAN port (1..8) so that i.e. USB3->0x53 which means USB interface 3rd channel
Definition at line 501 of file pkcan.cpp.
Referenced by configureCanboard().
getPortBitrate()
virtual uint32_t PKCanScan::getPortBitrate () inline virtual
returns the bitrate of that port [bits/sec] according to what CanModule buffers say. This is the setting used for setting up the hardware, after any default rules have been applied, but BEFORE any vendor specific encoding into obscure bitpatterns occurs. This happens at port opening and the bitrate can only be changed at that moment. So please call this method just after you have opened the port. But also since there is no hw interaction and it just returns a buffer, you may call it as often as you like.
Implements CanModule::CCanAccess.
Definition at line 68 of file pkcan.h.
getPortStatus()
uint32_t PKCanScan::getPortStatus () virtual
PCANBasic.h:113
Implements CanModule::CCanAccess.
Definition at line 109 of file pkcan.cpp.
References CANMODULE_STATUS_BP_PEAK, and m_pkCanHandle.
getReconnectAction()
virtual CanModule::ReconnectAction PKCanScan::getReconnectAction () inline virtual
read back the r.action
Implements CanModule::CCanAccess.
Definition at line 84 of file pkcan.h.
Referenced by CanReconnectionThread().
getReconnectCondition()
virtual CanModule::ReconnectAutoCondition PKCanScan::getReconnectCondition () inline virtual
read back the r.condition
Implements CanModule::CCanAccess.
Definition at line 83 of file pkcan.h.
Referenced by CanReconnectionThread(), and CanScanControlThread().
getStatistics()
void PKCanScan::getStatistics (CanStatistics & result) virtual
Implements CanModule::CCanAccess.
Definition at line 557 of file pkcan.cpp.
References CanModule::CanStatistics::beginNewRun(), CanModule::CanStatistics::computeDerived(), m_baudRate, and m_statistics.
getTPCANHandle()
TPCANHandle PKCanScan::getTPCANHandle () inline
Definition at line 89 of file pkcan.h.
Referenced by CanReconnectionThread().
logItHandle()
Log::LogComponentHandle PKCanScan::logItHandle () inline
Definition at line 76 of file pkcan.h.
operator=()
PKCanScan& PKCanScan::operator= (PKCanScan const & other) delete
sendErrorCode()
bool PKCanScan::sendErrorCode (long status) private
Definition at line 408 of file pkcan.cpp.
References CanModule::CCanAccess::canMessageError, CanModule::convertTimepointToTimeval(), CanModule::currentTimeTimeval(), getErrorMessage(), m_busStatus, and m_pkCanHandle.
Referenced by sendMessage(), and sendRemoteRequest().
sendMessage()
bool PKCanScan::sendMessage (short cobID, unsigned char len, unsigned char * message, bool rtr = false) virtual
method to send a CAN message to the peak module. we use the standard API "PCAN-Basic" for this for windows and we talk only over USB to fixed bitrate modules. The flexible bitrate (FD) modules can be implemented later as well: for this we need more parameters to pass and a switch between CAN_Write and CAN_WriteFD.
Implements CanModule::CCanAccess.
Definition at line 431 of file pkcan.cpp.
References CanModule::canMessage2ToString(), m_pkCanHandle, m_statistics, MLOGPK, CanModule::CanStatistics::onTransmit(), sendErrorCode(), CanModule::CanStatistics::setTimeSinceTransmitted(), and CanModule::CCanAccess::triggerReconnectionThread().
sendRemoteRequest()
bool PKCanScan::sendRemoteRequest (short cobID) virtual
Method that sends a remote request trough the can bus channel. If the method createBus was not called before this, sendMessage will fail, as there is no can bus channel to send the request trough. Similar to sendMessage, but it sends an special message reserved for requests.
Parameters
cobID Identifier that will be used for the request.
Returns
Was the sent request successful ?
Implements CanModule::CCanAccess.
Definition at line 478 of file pkcan.cpp.
References m_pkCanHandle, and sendErrorCode().
setReconnectBehavior()
virtual void PKCanScan::setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action) inline virtual
configuring the reconnection behavior: a condition triggers an action. The implementation is implementation-specific because not all vendor APIs permit the same behavior: not all combinations are available for all vendors/implementations. The implemented reconnection behavior is standardized nevertheless: "you get what you see". Foe each CanBus you have to choose one condition and one action. Condition detection and action execution are then automatic inside CanModule.
Parameters
CanModule::ReconnectAutoCondition cond
sendFail (default): a reconnection is triggered automatically if a send on the canBus fails. The number of failed sends can be set (default is 10). The failed sending must be strictly consecutive, if there is a succeeded sending, the internal counting restarts.
timeoutOnReception: the last time of a successful reception on a given channel can be monitored. If the last reception is older than 120 sec a reset is triggered automatically. This last successful reception time is calculated each time a send is invoked. The timeout is specified in seconds, default is 120sec.
never: this condition is always false and therefore no automatic reconnection action will be triggered. You can still call the explicit method reconnect(<action>) but it is up to the client (server) to decide when.
CanModule::ReconnectAction action
singleBus (default): a single connection (canbus, channel) is reset and reception handler is reconnected.
wholeBridge if available, the whole bridge is reset, affecting all physical channels on that bridge. Only available for anagate. If a bridge is shared between multiple tasks, all channels across tasks are reset, affecting all tasks connected to that bridge. Evidently, a given channel must only be used by at most one task.
Implements CanModule::CCanAccess.
Definition at line 77 of file pkcan.h.
setReconnectFailedSendCount()
virtual void PKCanScan::setReconnectFailedSendCount (unsigned int c) inline virtual
set the counter for failed consecutive sending attempts, for reconnection. default is 10.
Implements CanModule::CCanAccess.
Definition at line 82 of file pkcan.h.
setReconnectReceptionTimeout()
virtual void PKCanScan::setReconnectReceptionTimeout (unsigned int timeout) inline virtual
set the timout interval for message reception, for the reconnection behaviour. Units is seconds, default is 120.
Implements CanModule::CCanAccess.
Definition at line 81 of file pkcan.h.
stopBus()
void PKCanScan::stopBus () virtual
notify the main thread to finish and delete the bus from the map of connections
Implements CanModule::CCanAccess.
Definition at line 79 of file pkcan.cpp.
References m_busMap, m_busName, m_CanScanThreadRunEnableFlag, m_idCanScanThread, m_pkCanHandle, MLOGPK, and peakReconnectMutex.
Referenced by ~PKCanScan().
Member Data Documentation
m_baudRate
unsigned int PKCanScan::m_baudRate private
Definition at line 108 of file pkcan.h.
Referenced by configureCanboard(), and getStatistics().
m_busMap
std::map< std::string, std::string > PKCanScan::m_busMap static
Copyright CERN, 2015. All rights not expressly granted are reserved.
AnaCanScan.cpp
Created on: Mar 17, 2015 Author: pnikiel, vfilimon, quasar team mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
PEAK bridge integration for windows
Definition at line 75 of file pkcan.h.
Referenced by createBus(), and stopBus().
m_busName
std::string PKCanScan::m_busName private
Definition at line 109 of file pkcan.h.
Referenced by createBus(), and stopBus().
m_busParameters
std::string PKCanScan::m_busParameters private
Definition at line 110 of file pkcan.h.
Referenced by createBus().
m_busStatus
TPCANStatus PKCanScan::m_busStatus private
Definition at line 105 of file pkcan.h.
Referenced by sendErrorCode().
m_CanScanThreadRunEnableFlag
bool PKCanScan::m_CanScanThreadRunEnableFlag private
Definition at line 106 of file pkcan.h.
Referenced by CanScanControlThread(), and stopBus().
m_hCanScanThread
HANDLE PKCanScan::m_hCanScanThread private
Definition at line 116 of file pkcan.h.
Referenced by createBus().
m_idCanScanThread
DWORD PKCanScan::m_idCanScanThread private
Definition at line 118 of file pkcan.h.
Referenced by createBus(), and stopBus().
m_idPeakReconnectionThread
DWORD PKCanScan::m_idPeakReconnectionThread private
Definition at line 119 of file pkcan.h.
Referenced by createBus().
m_logItHandlePk
Log::LogComponentHandle PKCanScan::m_logItHandlePk private
Definition at line 95 of file pkcan.h.
Referenced by createBus().
m_PeakReconnectionThread
HANDLE PKCanScan::m_PeakReconnectionThread private
Definition at line 117 of file pkcan.h.
Referenced by createBus().
m_pkCanHandle
TPCANHandle PKCanScan::m_pkCanHandle private
Definition at line 112 of file pkcan.h.
Referenced by CanScanControlThread(), configureCanboard(), createBus(), getPortStatus(), sendErrorCode(), sendMessage(), sendRemoteRequest(), and stopBus().
m_statistics
CanStatistics PKCanScan::m_statistics private
Definition at line 104 of file pkcan.h.
Referenced by CanScanControlThread(), getStatistics(), PKCanScan(), and sendMessage().
The documentation for this class was generated from the following files:
CanInterfaceImplementations/pkcan/pkcan.h
CanInterfaceImplementations/pkcan/pkcan.cpp