CanModule: CanModule::CCanAccess Class Reference
CanModule::CCanAccess Class Reference abstract
#include <CCanAccess.h>
Public Member Functions
CCanAccess ()
virtual bool sendRemoteRequest (short cobID)=0
virtual int createBus (const string name, const string parameters)=0
virtual bool sendMessage (short cobID, unsigned char len, unsigned char *message, bool rtr=false)=0
virtual bool sendMessage (CanMessage *canm)
std::string & getBusName ()
virtual uint32_t getPortStatus ()=0
virtual uint32_t getPortBitrate ()=0
virtual ~CCanAccess ()
virtual void getStatistics (CanStatistics &result)=0
bool initialiseLogging (LogItInstance *remoteInstance)
LogItInstance * getLogItInstance ()
vector< string > parseNameAndParameters (string name, string parameters)
void triggerReconnectionThread ()
void waitForReconnectionThreadTrigger ()
void decreaseSendFailedCountdown ()
void resetSendFailedCountdown ()
virtual void setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action)=0
virtual void setReconnectReceptionTimeout (unsigned int timeout)=0
virtual void setReconnectFailedSendCount (unsigned int c)=0
virtual
CanModule::ReconnectAutoCondition getReconnectCondition ()=0
virtual CanModule::ReconnectAction getReconnectAction ()=0
virtual void stopBus ()=0
Static Public Member Functions
static std::string reconnectConditionString (CanModule::ReconnectAutoCondition c)
static std::string reconnectActionString (CanModule::ReconnectAction c)
Public Attributes
boost::signals2::signal< void(const
CanMessage &) > canMessageCame
boost::signals2::signal< void(const
int, const char *, timeval &) > canMessageError
Protected Member Functions
bool hasTimeoutOnReception ()
void resetTimeoutOnReception ()
void resetTimeNow ()
Protected Attributes
string m_sBusName
CanParameters m_CanParameters
CanModule::ReconnectAutoCondition m_reconnectCondition
CanModule::ReconnectAction m_reconnectAction
atomic_uint m_timeoutOnReception
atomic_int m_failedSendCountdown
atomic_uint m_maxFailedSendCount
std::thread * m_hCanReconnectionThread
atomic_bool m_reconnectTrigger
std::mutex m_reconnection_mtx
std::condition_variable m_reconnection_cv
Private Attributes
Log::LogComponentHandle m_lh
LogItInstance * m_logItRemoteInstance
high_resolution_clock::time_point m_dnow
high_resolution_clock::time_point m_dreceived
high_resolution_clock::time_point m_dtransmitted
high_resolution_clock::time_point m_dopen
Detailed Description
Definition at line 150 of file CCanAccess.h.
Constructor & Destructor Documentation
CanModule::CCanAccess::CCanAccess () inline
Definition at line 155 of file CCanAccess.h.
References resetTimeNow(), and resetTimeoutOnReception().
virtual CanModule::CCanAccess::~CCanAccess () inline virtual
Definition at line 325 of file CCanAccess.h.
Member Function Documentation
virtual int CanModule::CCanAccess::createBus (const string name, const string parameters) pure virtual
Method that initialises a can bus channel. The following methods called upon the same object will be using this initialised channel.
Parameters
name,: Name of the can bus channel. The specific mapping will change depending on the interface used. For example, accessing channel 0 for the systec interface would be using name "st:9", while in socket can the same channel would be "sock:can0". anagate interface would be an:192.168.1.2 for the default ip address
parameters,: Different parameters used for the initialisation. For using the parameters already in the hardware just set this to "Unspecified". anagate: pass the ip number
Returns
: init OK, bus was created = OK = 0 init OK, bus was skipped because it exists already = 1 init failed = -1
Implemented in AnaCanScan, CSockCanScan, STCanScan, PKCanScan, and MockCanAccess.
Referenced by CanModule::CanLibLoader::openCanBus().
void CanModule::CCanAccess::decreaseSendFailedCountdown () inline
Definition at line 438 of file CCanAccess.h.
References m_failedSendCountdown, and m_lh.
Referenced by CSockCanScan::sendMessage(), and AnaCanScan::sendMessage().
std::string& CanModule::CCanAccess::getBusName () inline
Returns the can bus name
Definition at line 222 of file CCanAccess.h.
References m_sBusName.
Referenced by AnaCanScan::CanReconnectionThread(), PKCanScan::CanScanControlThread(), CSockCanScan::clearErrorMessage(), CanModule::CanBusAccess::closeCanBus(), CanModule::CanLibLoader::closeCanBus(), CanModule::Diag::delete_maps(), CanModule::Diag::insert_maps(), CSockCanScan::sendErrorMessage(), and AnaCanScan::sendMessage().
LogItInstance* CanModule::CCanAccess::getLogItInstance () inline
the LogIt instance is NOT shared by inheritance in windows, the instance has to be passed explicitly from the parent
Definition at line 350 of file CCanAccess.h.
References m_logItRemoteInstance.
virtual uint32_t CanModule::CCanAccess::getPortBitrate () pure virtual
returns the bitrate of that port [bits/sec] according to what CanModule buffers say. This is the setting used for setting up the hardware, after any default rules have been applied, but BEFORE any vendor specific encoding into obscure bitpatterns occurs. This happens at port opening and the bitrate can only be changed at that moment. So please call this method just after you have opened the port. But also since there is no hw interaction and it just returns a buffer, you may call it as often as you like. Default bitrate is always 125000bits/s if "Unspecified"
Implemented in AnaCanScan, CSockCanScan, PKCanScan, STCanScan, and MockCanAccess.
virtual uint32_t CanModule::CCanAccess::getPortStatus () pure virtual
according to vendor and OS, acquire bus status, and return one uint32_t bitpattern which has the same rules for all vendors. In fact the status for vendors is too different to be abstracted into a common bitpattern.
the implementation occupies the highest nibble, and it is a counter (see CANMODULE_STATUS_BP_SOCK etc)
0x1<<28 = sock (linux)
0x2<<28 = anagate (linux, windows)
0x3<<28 = peak (windows)
0x4<<28 = systec (windows)
0x5<<28....0xf<<28 = unused, for future use
the **specific status** occupies bits b0..b27, and it is a (composed) implementation specific bitpattern
Parameters
sock (linux): [ see can_netlink.h enum can_state ]
b0: 0x1 = CAN_STATE_ERROR_ACTIVE : RX/TX error count < 96
b1: 0x2 = CAN_STATE_ERROR_WARNING : RX/TX error count < 128
b2: 0x4 = CAN_STATE_ERROR_PASSIVE : RX/TX error count < 256
b3: 0x8 = CAN_STATE_BUS_OFF : RX/TX error count >= 256
b4: 0x10 = CAN_STATE_STOPPED : Device is stopped
b5: 0x20 = CAN_STATE_SLEEPING : Device is sleeping
b6...b27 unused
anagate (linux, windows): [ see CANDeviceConnectState ] CANCanDeviceConnectState , translate from counter (0 does not exists, thank you anagate)
1 = DISCONNECTED :
2 = CONNECTING :
3 = CONNECTED
4 = DISCONNECTING
5 = NOT_INITIALIZED
b3...b27: unused
I translate this into a simple bitpattern which is a counter : 000(does not occur), 001, 010, 011, 100, 101. Actually 011 means OK therefore. great.
peak (windows): see PCANBasic.h:113
#define PCAN_ERROR_OK 0x00000U // No error
#define PCAN_ERROR_XMTFULL 0x00001U // Transmit buffer in CAN controller is full
#define PCAN_ERROR_OVERRUN 0x00002U // CAN controller was read too late
#define PCAN_ERROR_BUSLIGHT 0x00004U // Bus error: an error counter reached the 'light' limit
#define PCAN_ERROR_BUSHEAVY 0x00008U // Bus error: an error counter reached the 'heavy' limit
#define PCAN_ERROR_BUSWARNING PCAN_ERROR_BUSHEAVY // Bus error: an error counter reached the 'warning' limit
#define PCAN_ERROR_BUSPASSIVE 0x40000U // Bus error: the CAN controller is error passive
#define PCAN_ERROR_BUSOFF 0x00010U // Bus error: the CAN controller is in bus-off state
#define PCAN_ERROR_ANYBUSERR (PCAN_ERROR_BUSWARNING | PCAN_ERROR_BUSLIGHT | PCAN_ERROR_BUSHEAVY | PCAN_ERROR_BUSOFF | PCAN_ERROR_BUSPASSIVE) // Mask for all bus errors
#define PCAN_ERROR_QRCVEMPTY 0x00020U // Receive queue is empty
#define PCAN_ERROR_QOVERRUN 0x00040U // Receive queue was read too late
#define PCAN_ERROR_QXMTFULL 0x00080U // Transmit queue is full
#define PCAN_ERROR_REGTEST 0x00100U // Test of the CAN controller hardware registers failed (no hardware found)
#define PCAN_ERROR_NODRIVER 0x00200U // Driver not loaded
#define PCAN_ERROR_HWINUSE 0x00400U // Hardware already in use by a Net
#define PCAN_ERROR_NETINUSE 0x00800U // A Client is already connected to the Net
#define PCAN_ERROR_ILLHW 0x01400U // Hardware handle is invalid
#define PCAN_ERROR_ILLNET 0x01800U // Net handle is invalid
#define PCAN_ERROR_ILLCLIENT 0x01C00U // Client handle is invalid
#define PCAN_ERROR_ILLHANDLE (PCAN_ERROR_ILLHW | PCAN_ERROR_ILLNET | PCAN_ERROR_ILLCLIENT) // Mask for all handle errors
#define PCAN_ERROR_RESOURCE 0x02000U // Resource (FIFO, Client, timeout) cannot be created
#define PCAN_ERROR_ILLPARAMTYPE 0x04000U // Invalid parameter
#define PCAN_ERROR_ILLPARAMVAL 0x08000U // Invalid parameter value
#define PCAN_ERROR_UNKNOWN 0x10000U // Unknown error
#define PCAN_ERROR_ILLDATA 0x20000U // Invalid data, function, or action
#define PCAN_ERROR_CAUTION 0x2000000U // An operation was successfully carried out, however, irregularities were registered
#define PCAN_ERROR_INITIALIZE 0x4000000U // Channel is not initialized [Value was changed from 0x40000 to 0x4000000]
#define PCAN_ERROR_ILLOPERATION 0x8000000U // Invalid operation [Value was changed from 0x80000 to 0x8000000]
systec (windows): [ see UcanGetStatus table19 (for CAN) and table20 (for USB) ]. This is a combination of socketcan bits and usb bits
b0: 0x1: tx overrun
b1: 0x2: rx overrun
b2: 0x4: error limit1 exceeded: warning limit
b3: 0x8: error limit2 exceeded: error passive
b4: 0x10: can controller is off
b5: unused
b6: 0x40: rx buffer overrun
b7: 0x80: tx buffer overrun
b8..b9: unused
b10: 0x400: transmit timeout, message dropped
b12..b11: unused
b13: 0x2000: module/usb got reset because of polling failure per second
b14: 0x4000: module/usb got reset because watchdog was not triggered
b15...b27: unused
Implemented in AnaCanScan, CSockCanScan, PKCanScan, STCanScan, and MockCanAccess.
virtual CanModule::ReconnectAction CanModule::CCanAccess::getReconnectAction () pure virtual
read back the r.action
Implemented in CSockCanScan, AnaCanScan, PKCanScan, STCanScan, and MockCanAccess.
virtual CanModule::ReconnectAutoCondition CanModule::CCanAccess::getReconnectCondition () pure virtual
read back the r.condition
Implemented in CSockCanScan, AnaCanScan, PKCanScan, STCanScan, and MockCanAccess.
virtual void CanModule::CCanAccess::getStatistics (CanStatistics & result) pure virtual
Implemented in AnaCanScan, PKCanScan, CSockCanScan, STCanScan, and MockCanAccess.
bool CanModule::CCanAccess::hasTimeoutOnReception () inline protected
compared to the last received message, are we in timeout?
Definition at line 552 of file CCanAccess.h.
References m_dnow, m_dopen, and m_timeoutOnReception.
Referenced by CSockCanScan::CanReconnectionThread(), STCanScan::CanScanControlThread(), PKCanScan::CanScanControlThread(), and AnaCanScan::sendMessage().
bool CanModule::CCanAccess::initialiseLogging (LogItInstance * remoteInstance) inline
Definition at line 339 of file CCanAccess.h.
References m_logItRemoteInstance.
Referenced by CanModule::CanLibLoader::openCanBus().
vector<string> CanModule::CCanAccess::parseNameAndParameters (string name, string parameters) inline
care for different syntax: "sock:0" => sock:can0 "sock:can0" => "sock:can0" "sock:vcan0" => "sock:vcan0"
"sock:whatsoever0" => "sock:can0" "sock:whatsoevervcan0" => "sock:vcan0" "sock:wvcanhatso0" => "sock:vcan0"
if you specify only an integer portnumber we default to "can" if you specify ":can" we stay with "can" if you specify ":vcan" we stay with "vcan" if you specify anything else which contains a string and an integer, we use can if you specify anything else which contains a string containing ":vcan" and an integer, we use vcan so basically you have the freedom to call your devices as you want. Maybe this is too much freedom.
Definition at line 360 of file CCanAccess.h.
References m_CanParameters, m_lh, m_sBusName, and CanModule::CanParameters::scanParameters().
Referenced by STCanScan::configureCanBoard(), PKCanScan::configureCanboard(), CSockCanScan::configureCanBoard(), and AnaCanScan::configureCanBoard().
static std::string CanModule::CCanAccess::reconnectActionString (CanModule::ReconnectAction c) inline static
just translate the ugly r.action enum into a user-friendly string for convenience and logging.
Definition at line 519 of file CCanAccess.h.
References CanModule::allBusesOnBridge, and CanModule::singleBus.
Referenced by PKCanScan::CanReconnectionThread(), CSockCanScan::CanReconnectionThread(), AnaCanScan::CanReconnectionThread(), STCanScan::CanScanControlThread(), and STCanScan::sendMessage().
static std::string CanModule::CCanAccess::reconnectConditionString (CanModule::ReconnectAutoCondition c) inline static
just translate the ugly r.condition enum into a user-friendly string for convenience and logging.
Definition at line 507 of file CCanAccess.h.
References CanModule::never, CanModule::sendFail, and CanModule::timeoutOnReception.
Referenced by PKCanScan::CanReconnectionThread(), CSockCanScan::CanReconnectionThread(), AnaCanScan::CanReconnectionThread(), STCanScan::CanScanControlThread(), STCanScan::sendMessage(), and AnaCanScan::sendMessage().
void CanModule::CCanAccess::resetSendFailedCountdown () inline
Definition at line 444 of file CCanAccess.h.
References m_failedSendCountdown, m_lh, and m_maxFailedSendCount.
Referenced by PKCanScan::CanReconnectionThread(), CSockCanScan::CanReconnectionThread(), AnaCanScan::CanReconnectionThread(), and CSockCanScan::sendMessage().
void CanModule::CCanAccess::resetTimeNow () inline protected
Definition at line 565 of file CCanAccess.h.
References m_dnow.
Referenced by CCanAccess().
void CanModule::CCanAccess::resetTimeoutOnReception () inline protected
reset the internal reconnection timeout counter
Definition at line 562 of file CCanAccess.h.
References m_dreceived.
Referenced by AnaCanScan::callbackOnRecieve(), PKCanScan::CanReconnectionThread(), CSockCanScan::CanReconnectionThread(), AnaCanScan::CanReconnectionThread(), STCanScan::CanScanControlThread(), PKCanScan::CanScanControlThread(), and CCanAccess().
virtual bool CanModule::CCanAccess::sendMessage (short cobID, unsigned char len, unsigned char * message, bool rtr = false) pure virtual
Method that sends a message through the can bus channel. If the method createBUS was not called before this, sendMessage will fail, as there is no can bus channel to send a message through.
Parameters
cobID,: Identifier that will be used for the message.
len,: Length of the message. If the message is bigger than 8 characters, it will be split into separate 8 characters messages.
message,: Message to be sent through the can bus.
rtr,: activate the Remote Transmission Request flag. Having this flag in a message with data/len is not part of the CAN standard, but since some hardware uses it anyway, the option to use it is provided.
Returns
: Was the initialisation process successful?
Implemented in AnaCanScan, PKCanScan, CSockCanScan, STCanScan, and MockCanAccess.
Referenced by sendMessage().
virtual bool CanModule::CCanAccess::sendMessage (CanMessage * canm) inline virtual
Reimplemented in AnaCanScan.
Definition at line 208 of file CCanAccess.h.
References CanMsgStruct::c_data, CanMsgStruct::c_dlc, CanMsgStruct::c_id, CanMsgStruct::c_rtr, m_lh, and sendMessage().
virtual bool CanModule::CCanAccess::sendRemoteRequest (short cobID) pure virtual
Method that sends a remote request trough the can bus channel. If the method createBus was not called before this, sendMessage will fail, as there is no can bus channel to send the request trough. Similar to sendMessage, but it sends an special message reserved for requests.
Parameters
cobID,: Identifier that will be used for the request.
Returns
: Was the initialisation process successful?
Implemented in AnaCanScan, PKCanScan, STCanScan, CSockCanScan, and MockCanAccess.
virtual void CanModule::CCanAccess::setReconnectBehavior (CanModule::ReconnectAutoCondition cond, CanModule::ReconnectAction action) pure virtual
configuring the reconnection behavior: a condition triggers an action. The implementation is implementation-specific because not all vendor APIs permit the same behavior: not all combinations are available for all vendors/implementations. The implemented reconnection behavior is standardized nevertheless: "you get what you see". Foe each CanBus you have to choose one condition and one action. Condition detection and action execution are then automatic inside CanModule.
Parameters
CanModule::ReconnectAutoCondition cond
sendFail (default): a reconnection is triggered automatically if a send on the canBus fails. The number of failed sends can be set (default is 10). The failed sending must be strictly consecutive, if there is a succeeded sending, the internal counting restarts.
timeoutOnReception: the last time of a successful reception on a given channel can be monitored. If the last reception is older than 120 sec a reset is triggered automatically. This last successful reception time is calculated each time a send is invoked. The timeout is specified in seconds, default is 120sec.
never: this condition is always false and therefore no automatic reconnection action will be triggered. You can still call the explicit method reconnect(<action>) but it is up to the client (server) to decide when.
CanModule::ReconnectAction action
singleBus (default): a single connection (canbus, channel) is reset and reception handler is reconnected.
wholeBridge if available, the whole bridge is reset, affecting all physical channels on that bridge. Only available for anagate. If a bridge is shared between multiple tasks, all channels across tasks are reset, affecting all tasks connected to that bridge. Evidently, a given channel must only be used by at most one task.
Implemented in CSockCanScan, AnaCanScan, PKCanScan, STCanScan, and MockCanAccess.
virtual void CanModule::CCanAccess::setReconnectFailedSendCount (unsigned int c) pure virtual
set the counter for failed consecutive sending attempts, for reconnection. default is 10.
Implemented in CSockCanScan, AnaCanScan, PKCanScan, STCanScan, and MockCanAccess.
virtual void CanModule::CCanAccess::setReconnectReceptionTimeout (unsigned int timeout) pure virtual
set the timout interval for message reception, for the reconnection behaviour. Units is seconds, default is 120.
Implemented in CSockCanScan, AnaCanScan, PKCanScan, STCanScan, and MockCanAccess.
virtual void CanModule::CCanAccess::stopBus () pure virtual
force implementation
Implemented in CSockCanScan, AnaCanScan, PKCanScan, STCanScan, and MockCanAccess.
Referenced by CanModule::CanLibLoader::closeCanBus().
void CanModule::CCanAccess::triggerReconnectionThread () inline
Definition at line 425 of file CCanAccess.h.
References m_reconnection_cv, and m_reconnectTrigger.
Referenced by PKCanScan::CanScanControlThread(), CSockCanScan::CanScanControlThread(), CSockCanScan::sendMessage(), PKCanScan::sendMessage(), and AnaCanScan::sendMessage().
void CanModule::CCanAccess::waitForReconnectionThreadTrigger () inline
Definition at line 432 of file CCanAccess.h.
References m_reconnection_cv, m_reconnection_mtx, and m_reconnectTrigger.
Referenced by PKCanScan::CanReconnectionThread(), CSockCanScan::CanReconnectionThread(), and AnaCanScan::CanReconnectionThread().
Member Data Documentation
boost::signals2::signal<void (const CanMessage &) > CanModule::CCanAccess::canMessageCame
Definition at line 323 of file CCanAccess.h.
Referenced by AnaCanScan::callbackOnRecieve(), STCanScan::CanScanControlThread(), PKCanScan::CanScanControlThread(), and MockCanAccess::sendMessage().
boost::signals2::signal<void (const int,const char *,timeval &) > CanModule::CCanAccess::canMessageError
Definition at line 325 of file CCanAccess.h.
Referenced by CSockCanScan::clearErrorMessage(), AnaCanScan::sendAnErrorMessage(), STCanScan::sendErrorCode(), PKCanScan::sendErrorCode(), CSockCanScan::sendErrorMessage(), and CSockCanScan::updateInitialError().
CanParameters CanModule::CCanAccess::m_CanParameters protected
Definition at line 535 of file CCanAccess.h.
Referenced by STCanScan::configureCanBoard(), PKCanScan::configureCanboard(), AnaCanScan::configureCanBoard(), AnaCanScan::connectReceptionHandler(), MockCanAccess::getPortBitrate(), CSockCanScan::getStatistics(), CSockCanScan::openCanPort(), AnaCanScan::openCanPort(), and parseNameAndParameters().
high_resolution_clock::time_point CanModule::CCanAccess::m_dnow private
Definition at line 572 of file CCanAccess.h.
Referenced by hasTimeoutOnReception(), and resetTimeNow().
high_resolution_clock::time_point CanModule::CCanAccess::m_dopen private
Definition at line 572 of file CCanAccess.h.
Referenced by hasTimeoutOnReception().
high_resolution_clock::time_point CanModule::CCanAccess::m_dreceived private
Definition at line 572 of file CCanAccess.h.
Referenced by resetTimeoutOnReception().
high_resolution_clock::time_point CanModule::CCanAccess::m_dtransmitted private
Definition at line 572 of file CCanAccess.h.
atomic_int CanModule::CCanAccess::m_failedSendCountdown protected
Definition at line 541 of file CCanAccess.h.
Referenced by AnaCanScan::AnaCanScan(), CSockCanScan::CanReconnectionThread(), AnaCanScan::CanReconnectionThread(), CSockCanScan::CSockCanScan(), decreaseSendFailedCountdown(), MockCanAccess::MockCanAccess(), PKCanScan::PKCanScan(), resetSendFailedCountdown(), STCanScan::sendMessage(), MockCanAccess::setReconnectFailedSendCount(), and STCanScan::STCanScan().
std::thread* CanModule::CCanAccess::m_hCanReconnectionThread protected
Definition at line 543 of file CCanAccess.h.
Referenced by AnaCanScan::AnaCanScan(), and CSockCanScan::createBus().
Log::LogComponentHandle CanModule::CCanAccess::m_lh private
Definition at line 570 of file CCanAccess.h.
Referenced by decreaseSendFailedCountdown(), parseNameAndParameters(), resetSendFailedCountdown(), and sendMessage().
LogItInstance* CanModule::CCanAccess::m_logItRemoteInstance private
Definition at line 571 of file CCanAccess.h.
Referenced by getLogItInstance(), and initialiseLogging().
atomic_uint CanModule::CCanAccess::m_maxFailedSendCount protected
Definition at line 542 of file CCanAccess.h.
Referenced by AnaCanScan::AnaCanScan(), CSockCanScan::CSockCanScan(), MockCanAccess::MockCanAccess(), PKCanScan::PKCanScan(), resetSendFailedCountdown(), STCanScan::sendMessage(), MockCanAccess::setReconnectFailedSendCount(), and STCanScan::STCanScan().
CanModule::ReconnectAction CanModule::CCanAccess::m_reconnectAction protected
Definition at line 539 of file CCanAccess.h.
Referenced by CSockCanScan::CanReconnectionThread(), AnaCanScan::CanReconnectionThread(), MockCanAccess::getReconnectAction(), and STCanScan::sendMessage().
CanModule::ReconnectAutoCondition CanModule::CCanAccess::m_reconnectCondition protected
Definition at line 538 of file CCanAccess.h.
Referenced by AnaCanScan::callbackOnRecieve(), CSockCanScan::CanReconnectionThread(), AnaCanScan::CanReconnectionThread(), MockCanAccess::getReconnectCondition(), STCanScan::sendMessage(), and AnaCanScan::sendMessage().
std::condition_variable CanModule::CCanAccess::m_reconnection_cv protected
Definition at line 546 of file CCanAccess.h.
Referenced by triggerReconnectionThread(), and waitForReconnectionThreadTrigger().
std::mutex CanModule::CCanAccess::m_reconnection_mtx protected
Definition at line 545 of file CCanAccess.h.
Referenced by waitForReconnectionThreadTrigger().
atomic_bool CanModule::CCanAccess::m_reconnectTrigger protected
Definition at line 544 of file CCanAccess.h.
Referenced by triggerReconnectionThread(), and waitForReconnectionThreadTrigger().
string CanModule::CCanAccess::m_sBusName protected
Definition at line 534 of file CCanAccess.h.
Referenced by PKCanScan::configureCanboard(), MockCanAccess::createBus(), STCanScan::createBus(), getBusName(), and parseNameAndParameters().
atomic_uint CanModule::CCanAccess::m_timeoutOnReception protected
Definition at line 540 of file CCanAccess.h.
Referenced by hasTimeoutOnReception(), and MockCanAccess::setReconnectReceptionTimeout().
The documentation for this class was generated from the following file:
CanInterface/include/CCanAccess.h