CanModule: CanModule::CanBusAccess Class Reference
CanModule::CanBusAccess Class Reference
#include <CanBusAccess.h>
Public Member Functions
CanBusAccess ()
CCanAccess * openCanBus (string name, string parameters)
void closeCanBus (CCanAccess *cca)
Private Member Functions
bool isCanPortOpen (string pn)
Private Attributes
map< string, CanLibLoader * > m_libLoader_map
map< string, CCanAccess * > m_canAccess_map
Detailed Description
CanBusAccess class ensure a connection to can hardware. it can create the connection to different hardware at same time the syntax of the name is "name of component:name of the channel"
Definition at line 42 of file CanBusAccess.h.
Constructor & Destructor Documentation
CanBusAccess()
CanModule::CanBusAccess::CanBusAccess () inline
Definition at line 45 of file CanBusAccess.h.
Member Function Documentation
closeCanBus()
void CanModule::CanBusAccess::closeCanBus (CCanAccess * cca)
Definition at line 30 of file CanBusAccess.cpp.
References CanModule::CanLibLoader::closeCanBus(), CanModule::CCanAccess::getBusName(), and m_libLoader_map.
isCanPortOpen()
bool CanModule::CanBusAccess::isCanPortOpen (string pn) inline private
Definition at line 50 of file CanBusAccess.h.
openCanBus()
CCanAccess * CanModule::CanBusAccess::openCanBus (string name, string parameters)
Definition at line 45 of file CanBusAccess.cpp.
References CanModule::CanLibLoader::createInstance(), m_canAccess_map, m_libLoader_map, and CanModule::CanLibLoader::openCanBus().
Member Data Documentation
m_canAccess_map
map<string, CCanAccess *> CanModule::CanBusAccess::m_canAccess_map private
Definition at line 52 of file CanBusAccess.h.
Referenced by openCanBus().
m_libLoader_map
map<string, CanLibLoader *> CanModule::CanBusAccess::m_libLoader_map private
Definition at line 51 of file CanBusAccess.h.
Referenced by closeCanBus(), and openCanBus().
The documentation for this class was generated from the following files:
CanInterface/include/CanBusAccess.h
CanInterface/src/CanBusAccess.cpp