CanModule: CanModule::CanStatistics Class Reference
CanModule::CanStatistics Class Reference
#include <CanStatistics.h>
Classes
class Internals
Following is encapsulated as a class, to provide sane copying in assignment operator.
Public Member Functions
SHARED_LIB_EXPORT_DEFN CanStatistics ()
void beginNewRun ()
void computeDerived (unsigned int baudRate)
void onTransmit (unsigned int dataLength)
void onReceive (unsigned int dataLength)
unsigned int totalTransmitted ()
unsigned int totalReceived ()
float txRate ()
float rxRate ()
float busLoad ()
double timeSinceReceived ()
double timeSinceTransmitted ()
double timeSinceOpened ()
void setTimeSinceOpened ()
void setTimeSinceReceived ()
void setTimeSinceTransmitted ()
void operator= (const CanStatistics &other)
Private Attributes
std::atomic_uint_least32_t m_totalTransmitted
std::atomic_uint_least32_t m_totalReceived
std::atomic_uint_least32_t m_transmitted
Number of messaged in current statistic run.
std::atomic_uint_least32_t m_received
Number of messaged in current statistic run.
std::atomic_uint_least32_t m_transmittedOctets
std::atomic_uint_least32_t m_receivedOctets
std::chrono::high_resolution_clock::time_point m_hrnow
std::chrono::high_resolution_clock::time_point m_hrreceived
std::chrono::high_resolution_clock::time_point m_hrtransmitted
std::chrono::high_resolution_clock::time_point m_hropen
Internals m_internals
Detailed Description
Definition at line 35 of file CanStatistics.h.
Constructor & Destructor Documentation
CanStatistics()
CanModule::CanStatistics::CanStatistics ()
Definition at line 32 of file CanStatistics.cpp.
Member Function Documentation
beginNewRun()
void CanModule::CanStatistics::beginNewRun ()
Definition at line 41 of file CanStatistics.cpp.
References m_internals, CanModule::CanStatistics::Internals::m_observationStart, m_received, m_receivedOctets, m_transmitted, and m_transmittedOctets.
Referenced by AnaCanScan::AnaCanScan(), CSockCanScan::CSockCanScan(), MockCanAccess::getStatistics(), STCanScan::getStatistics(), CSockCanScan::getStatistics(), PKCanScan::getStatistics(), AnaCanScan::getStatistics(), MockCanAccess::MockCanAccess(), PKCanScan::PKCanScan(), and STCanScan::STCanScan().
busLoad()
float CanModule::CanStatistics::busLoad () inline
bus load in 0...1 (% * 100) of max bus speed (baudrate)
Definition at line 73 of file CanStatistics.h.
References CanModule::CanStatistics::Internals::m_busLoad, and m_internals.
computeDerived()
void CanModule::CanStatistics::computeDerived (unsigned int baudRate)
Definition at line 49 of file CanStatistics.cpp.
References CanModule::CanStatistics::Internals::m_busLoad, m_internals, CanModule::CanStatistics::Internals::m_observationStart, m_received, m_receivedOctets, CanModule::CanStatistics::Internals::m_receivedPerSec, m_transmitted, m_transmittedOctets, and CanModule::CanStatistics::Internals::m_transmittedPerSec.
Referenced by MockCanAccess::getStatistics(), STCanScan::getStatistics(), CSockCanScan::getStatistics(), PKCanScan::getStatistics(), and AnaCanScan::getStatistics().
onReceive()
void CanModule::CanStatistics::onReceive (unsigned int dataLength)
called when receiving a message dataLength is the user data size (DLC field)
Definition at line 76 of file CanStatistics.cpp.
References m_received, m_receivedOctets, m_totalReceived, and setTimeSinceReceived().
Referenced by STCanScan::CanScanControlThread(), PKCanScan::CanScanControlThread(), and AnaCanScan::statisticsOnRecieve().
onTransmit()
void CanModule::CanStatistics::onTransmit (unsigned int dataLength)
called when transmitting a message dataLength is the user data size (DLC field)
Definition at line 69 of file CanStatistics.cpp.
References m_totalTransmitted, m_transmitted, and m_transmittedOctets.
Referenced by MockCanAccess::sendMessage(), STCanScan::sendMessage(), PKCanScan::sendMessage(), AnaCanScan::sendMessage(), and MockCanAccess::sendRemoteRequest().
operator=()
void CanModule::CanStatistics::operator= (const CanStatistics & other)
Definition at line 84 of file CanStatistics.cpp.
References m_hrnow, m_hropen, m_hrreceived, m_hrtransmitted, m_internals, m_received, m_receivedOctets, m_totalReceived, m_totalTransmitted, m_transmitted, and m_transmittedOctets.
rxRate()
float CanModule::CanStatistics::rxRate () inline
reception rate bytes/s
Definition at line 68 of file CanStatistics.h.
References m_internals, and CanModule::CanStatistics::Internals::m_receivedPerSec.
setTimeSinceOpened()
void CanModule::CanStatistics::setTimeSinceOpened () inline
Definition at line 101 of file CanStatistics.h.
References m_hropen.
Referenced by AnaCanScan::AnaCanScan(), CSockCanScan::CSockCanScan(), MockCanAccess::MockCanAccess(), STCanScan::openCanPort(), CSockCanScan::openCanPort(), PKCanScan::PKCanScan(), and STCanScan::STCanScan().
setTimeSinceReceived()
void CanModule::CanStatistics::setTimeSinceReceived () inline
Definition at line 102 of file CanStatistics.h.
References m_hrreceived.
Referenced by STCanScan::CanScanControlThread(), PKCanScan::CanScanControlThread(), onReceive(), CSockCanScan::sendRemoteRequest(), and AnaCanScan::statisticsOnRecieve().
setTimeSinceTransmitted()
void CanModule::CanStatistics::setTimeSinceTransmitted () inline
Definition at line 103 of file CanStatistics.h.
References m_hrtransmitted.
Referenced by STCanScan::sendMessage(), PKCanScan::sendMessage(), and AnaCanScan::sendMessage().
timeSinceOpened()
double CanModule::CanStatistics::timeSinceOpened () inline
time since that bus was opened, in milliseconds with microseconds precision
Definition at line 96 of file CanStatistics.h.
References m_hrnow, and m_hropen.
timeSinceReceived()
double CanModule::CanStatistics::timeSinceReceived () inline
time since the last message was received in milliseconds with microseconds precision
Definition at line 78 of file CanStatistics.h.
References m_hrnow, and m_hrreceived.
timeSinceTransmitted()
double CanModule::CanStatistics::timeSinceTransmitted () inline
time since the last message was sent, in milliseconds with microseconds precision
Definition at line 87 of file CanStatistics.h.
References m_hrnow, and m_hrtransmitted.
totalReceived()
unsigned int CanModule::CanStatistics::totalReceived () inline
Definition at line 58 of file CanStatistics.h.
References m_totalReceived.
totalTransmitted()
unsigned int CanModule::CanStatistics::totalTransmitted () inline
Definition at line 57 of file CanStatistics.h.
References m_totalTransmitted.
txRate()
float CanModule::CanStatistics::txRate () inline
transmission rate bytes/s
Definition at line 63 of file CanStatistics.h.
References m_internals, and CanModule::CanStatistics::Internals::m_transmittedPerSec.
Member Data Documentation
m_hrnow
std::chrono::high_resolution_clock::time_point CanModule::CanStatistics::m_hrnow private
Definition at line 119 of file CanStatistics.h.
Referenced by operator=(), timeSinceOpened(), timeSinceReceived(), and timeSinceTransmitted().
m_hropen
std::chrono::high_resolution_clock::time_point CanModule::CanStatistics::m_hropen private
Definition at line 119 of file CanStatistics.h.
Referenced by operator=(), setTimeSinceOpened(), and timeSinceOpened().
m_hrreceived
std::chrono::high_resolution_clock::time_point CanModule::CanStatistics::m_hrreceived private
Definition at line 119 of file CanStatistics.h.
Referenced by operator=(), setTimeSinceReceived(), and timeSinceReceived().
m_hrtransmitted
std::chrono::high_resolution_clock::time_point CanModule::CanStatistics::m_hrtransmitted private
Definition at line 119 of file CanStatistics.h.
Referenced by operator=(), setTimeSinceTransmitted(), and timeSinceTransmitted().
m_internals
Internals CanModule::CanStatistics::m_internals private
Definition at line 131 of file CanStatistics.h.
Referenced by beginNewRun(), busLoad(), computeDerived(), operator=(), rxRate(), and txRate().
m_received
std::atomic_uint_least32_t CanModule::CanStatistics::m_received private
Number of messaged in current statistic run.
Definition at line 115 of file CanStatistics.h.
Referenced by beginNewRun(), computeDerived(), onReceive(), and operator=().
m_receivedOctets
std::atomic_uint_least32_t CanModule::CanStatistics::m_receivedOctets private
Definition at line 117 of file CanStatistics.h.
Referenced by beginNewRun(), computeDerived(), onReceive(), and operator=().
m_totalReceived
std::atomic_uint_least32_t CanModule::CanStatistics::m_totalReceived private
Definition at line 111 of file CanStatistics.h.
Referenced by onReceive(), operator=(), and totalReceived().
m_totalTransmitted
std::atomic_uint_least32_t CanModule::CanStatistics::m_totalTransmitted private
Definition at line 110 of file CanStatistics.h.
Referenced by onTransmit(), operator=(), and totalTransmitted().
m_transmitted
std::atomic_uint_least32_t CanModule::CanStatistics::m_transmitted private
Number of messaged in current statistic run.
Definition at line 113 of file CanStatistics.h.
Referenced by beginNewRun(), computeDerived(), onTransmit(), and operator=().
m_transmittedOctets
std::atomic_uint_least32_t CanModule::CanStatistics::m_transmittedOctets private
Definition at line 116 of file CanStatistics.h.
Referenced by beginNewRun(), computeDerived(), onTransmit(), and operator=().
The documentation for this class was generated from the following files:
CanInterface/include/CanStatistics.h
CanInterface/src/CanStatistics.cpp