CanModule: CanModule Namespace Reference
CanModule Namespace Reference
Classes
class CanLibLoader
class CanLibLoaderLin
class CanLibLoaderWin
class CanModuleUtils
struct CanParameters
class CanStatistics
class CCanAccess
class Diag
Typedefs
typedef CCanAccess * f_canAccess()
Enumerations
enum ReconnectAutoCondition { ReconnectAutoCondition::sendFail =0, ReconnectAutoCondition::timeoutOnReception, ReconnectAutoCondition::never }
enum ReconnectAction { ReconnectAction::singleBus =0, ReconnectAction::allBusesOnBridge }
Functions
timeval convertTimepointToTimeval (const std::chrono::system_clock::time_point &t1)
std::chrono::system_clock::time_point convertTimevalToTimepoint (const timeval &t1)
double CanModulesubtractTimeval (const std::chrono::system_clock::time_point &t1, const std::chrono::system_clock::time_point &t2)
std::chrono::system_clock::time_point currentTimeTimeval ()
std::string CanModuleerrnoToString ()
typedef __declspec (dllimport) CCanAccess *f_CCanAccess()
Variables
const std::string LogItComponentName = "CanModule"
std::mutex mtx
Detailed Description
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CanModuleUtils.h
Created on: Oct 22, 2014 Author: Piotr Nikiel piotr.nosp@m.@nik.nosp@m.iel.i.nosp@m.nfo
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CCanAccess.h
Created on: Apr 4, 2011 original author: vfilimon maintaining: mludwig, quasar team
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CanModuleUtils.cpp
Created on: Nov 24, 2014 Author: pnikiel * CanBusAccess.cpp
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CanModuleUtils.cpp
CanStatistics.cpp
Created on: Mar 17, 2015 Author: pnikiel
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CanLibLoader.h
Created on: Feb 22, 2012 Author: vfilimon mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CanLibLoaderLin.h
Created on: Feb 22, 2012 Author: vfilimon mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CanLibLoader.cpp
Created on: Feb 22, 2012 Author: vfilimon mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CanLibLoaderLin.cpp
Created on: Feb 22, 2012 Author: vfilimon mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
© Copyright CERN, 2015. All rights not expressly granted are reserved.
CanLibLoaderWin.cpp
Created on: Feb 22, 2012 Author: vfilimon mludwig at cern dot ch
This file is part of Quasar.
Quasar is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public Licence as published by the Free Software Foundation, either version 3 of the Licence.
Quasar is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public Licence for more details.
You should have received a copy of the GNU Lesser General Public License along with Quasar. If not, see http://www.gnu.org/licenses/.
Typedef Documentation
f_canAccess
typedef CCanAccess* CanModule::f_canAccess()
Definition at line 36 of file CanLibLoaderLin.cpp.
Enumeration Type Documentation
ReconnectAction
enum CanModule::ReconnectAction strong
a reconnect action is performed if it is triggered by a reconnect condition of that channel/bus.
Parameters
singleBus (default): only the bus in question (this object) is reconnected, including it's reply handler, using the available implementation and vendor API.
allBusesOnBridge all the buses/channels on the bridge where this channel/bus physically belongs to are reconnected. Only available for anagate, where the whole bridge can be reset using it's ip number.
hardReset the whole bridge receives some kind of "hard reset via software", only available for anagate (firmware reboot).
Enumerator
singleBus
allBusesOnBridge
Definition at line 109 of file CCanAccess.h.
ReconnectAutoCondition
enum CanModule::ReconnectAutoCondition strong
if a reconnect condition becomes true, a reconnect action is performed.
Parameters
sendFail (default): the number of allowed fails for a send attempt can be set (default=10).
timeoutOnReception the number of seconds during which no message was received can be set (default=120sec). If the timeout is exceeded the condition becomes true. For anagate, this condition is only checked before a sending attempt. For all others the condition is checked in the supervisory thread.
never this condition is never true, use it to switch off reconnection behavior. You might need this if you share a bridge between several tasks.
Enumerator
sendFail
timeoutOnReception
never
Definition at line 94 of file CCanAccess.h.
Function Documentation
__declspec()
typedef CanModule::__declspec (dllimport)
CanModuleerrnoToString()
std::string CanModule::CanModuleerrnoToString ()
Definition at line 32 of file CanModuleUtils.cpp.
Referenced by CSockCanScan::openCanPort(), and CSockCanScan::sendRemoteRequest().
CanModulesubtractTimeval()
double CanModule::CanModulesubtractTimeval (const std::chrono::system_clock::time_point & t1, const std::chrono::system_clock::time_point & t2)
Definition at line 76 of file CanModuleUtils.cpp.
convertTimepointToTimeval()
timeval CanModule::convertTimepointToTimeval (const std::chrono::system_clock::time_point & t1)
Definition at line 44 of file CanModuleUtils.cpp.
Referenced by STCanScan::CanScanControlThread(), InternalCallback(), STCanScan::sendErrorCode(), and PKCanScan::sendErrorCode().
convertTimevalToTimepoint()
std::chrono::system_clock::time_point CanModule::convertTimevalToTimepoint (const timeval & t1)
Definition at line 53 of file CanModuleUtils.cpp.
currentTimeTimeval()
std::chrono::system_clock::time_point CanModule::currentTimeTimeval ()
Definition at line 60 of file CanModuleUtils.cpp.
Referenced by STCanScan::CanScanControlThread(), InternalCallback(), STCanScan::sendErrorCode(), and PKCanScan::sendErrorCode().
Variable Documentation
LogItComponentName
const std::string CanModule::LogItComponentName = "CanModule"
Definition at line 50 of file CCanAccess.h.
Referenced by CanModule::CanLibLoader::CanLibLoader(), PKCanScan::createBus(), STCanScan::createBus(), CSockCanScan::createBus(), AnaCanScan::createBus(), CanModule::Diag::Diag(), CanModule::CanLibLoader::openCanBus(), and udevanalyserforpeak_ns::UdevAnalyserForPeak::UdevAnalyserForPeak().
mtx
std::mutex CanModule::mtx
Definition at line 19 of file Diag.cpp.
Referenced by CanModule::Diag::delete_maps(), and CanModule::Diag::insert_maps().