"""
Namespace for CAN device error codes
"""

from __future__ import annotations

__all__ = [
    "CAN_INVALID_BITRATE",
    "CAN_LOST_ARBITRATION",
    "CAN_NACK",
    "CAN_TX_BUFFER_OVERFLOW",
    "CAN_TX_ERROR",
    "INTERNAL_API_ERROR",
    "NOT_CONNECTED",
    "NO_ERROR",
    "SOCKET_ERROR",
    "SUCCESS",
    "TIMEOUT",
    "TOO_MANY_CONNECTIONS",
    "UNACKNOWLEDMENT",
    "UNKNOWN_CLOSE_ERROR",
    "UNKNOWN_OPEN_ERROR",
    "UNKNOWN_SEND_ERROR",
]
CAN_INVALID_BITRATE: int = -25
CAN_LOST_ARBITRATION: int = -24
CAN_NACK: int = -21
CAN_TX_BUFFER_OVERFLOW: int = -23
CAN_TX_ERROR: int = -22
INTERNAL_API_ERROR: int = -7
NOT_CONNECTED: int = -5
NO_ERROR: int = 0
SOCKET_ERROR: int = -2
SUCCESS: int = 0
TIMEOUT: int = -4
TOO_MANY_CONNECTIONS: int = -3
UNACKNOWLEDMENT: int = -6
UNKNOWN_CLOSE_ERROR: int = -40
UNKNOWN_OPEN_ERROR: int = -1
UNKNOWN_SEND_ERROR: int = -20
