if(EXISTS "${CMAKE_SOURCE_DIR}/.env")
    message(STATUS "Setting environment variables from .env file")
    file(STRINGS ${CMAKE_SOURCE_DIR}/.env ENV_VARS REGEX "^.*=.*$" ENCODING UTF-8)
    foreach(env_var ${ENV_VARS})
        string(REPLACE "=" ";" env_var_list ${env_var})
        list(GET env_var_list 0 var_name)
        list(GET env_var_list 1 var_value)
        set(ENV{${var_name}} ${var_value})
    endforeach()
else()
    message(STATUS ".env file not found, not setting environment variables")
endif()
