#!/bin/bash
# documentation.sh - make all the doc
# running in an updated ubuntu image with a decent tex, sphinx and breathe installation
# we are supposed to run in the Documentation directory
#
# 1.doxygen xml
# need to produce a Doxyfile if there is none
#
DOC_ROOT=`pwd`
cd ${DOC_ROOT}/.. && doxygen # run it in the src root

cd ${DOC_ROOT}
rm -rf ${DOC_ROOT}/doxygen-html
mv -v ${DOC_ROOT}/sphinx-source/doxygen-result/html ${DOC_ROOT}/doxygen-html

# doxygen xml should be in ${DOC_ROOT}/sphinx-source/doxygen-result/xml
ls -l ${DOC_ROOT}/sphinx-source/doxygen-result/xml


#
# 2. sphinx
# html tree, tex, pdf, qthelp
#
# using the doxygen xml in sphinx-source as input for sphinx
#SPHINX_BUILD=/usr/local/bin/sphinx-build
SPHINX_BUILD=`which sphinx-build`

${SPHINX_BUILD} -b html ${DOC_ROOT}/sphinx-source ${DOC_ROOT}/html

#mkdir -p ${DOC_ROOT}/sphinx-result/latex
#${SPHINX_BUILD} -b latex ${DOC_ROOT}/sphinx-source ${DOC_ROOT}/sphinx-result/latex

mkdir -p ${DOC_ROOT}/sphinx-result/qthelp
${SPHINX_BUILD} -b qthelp ${DOC_ROOT}/sphinx-source ${DOC_ROOT}/sphinx-result/qthelp


#
# 3. pdf from latex and move
#
#cd ${DOC_ROOT}/sphinx-result/latex && make
#mkdir -p ${DOC_ROOT}/pdf
#find ${DOC_ROOT}/sphinx-result/latex -name "*.pdf" -exec mv -v {} ${DOC_ROOT}/pdf \;
#
# move also the latex
#rm -rf ${DOC_ROOT}/latex
#mkdir -p ${DOC_ROOT}/latex
#mv -v ${DOC_ROOT}/sphinx-result/latex ${DOC_ROOT}
#
# move also the qthelp
rm -rf ${DOC_ROOT}/qthelp
mkdir -p ${DOC_ROOT}/qthelp
mv -v ${DOC_ROOT}/sphinx-result/qthelp ${DOC_ROOT}


# cleanup
rm -rf ./sphinx-result/latex/
rm -rf ./sphinx-result/.doctrees/*
rm -rf ./sphinx-source/doxygen-result/

# results are in ${DOC_ROOT}:
# html - sphinx generated tree
# doxygen-html - code tree
# pdf - generated by sphinx via latex
# latex - generated by sphinx
